# --------------------------------------
# Dicionário Mapeado Ficha 1156 - PréOp
# --------------------------------------

#Organiza as colunas mapeadas
preop_ls = {
	'diabetes': ['RB_DM_NAO_1', 'RB_DM_SIM_1'],
    'hipertensao': ['RB_HAS_NAO_1', 'RB_HAS_SIM_1'],
	'origem_do_paciente': ['RB_PS_UTI_ORIGEM_PACIENTE_1', 'RB_ELETICO_ORIGEM_PACIENTE_1'],
    'sintomas_duracao': ['RB_ANOS_SINTOMAS_FICHA_PRE_1', 'RB_DIAS_AO_SINTOMAS_FICHA_PRE_1', 'RB_MESES_SINTOMAS_FICHA_PRE_1'],
    'hipertensao_pulmonar_encam': ['RB_HIPERTENSAO_PULMONAR_NAO_1', 'RB_HIPERTENSAO_PULMONAR_SIM_1', 
                                   'RB_HIPERTENSAO_ARTERIAL_PULMONAR_NAO_COMORBIDADES_PRINCIPAIS_1', 'RB_HIPERTENSAO_ARTERIAL_PULMONAR_SIM_COMORBIDADES_PRINCIPAIS_1'],
	'valor_psap_encam': ['RB_HIPERTENSAO_ARTERIAL_PULMONAR_SIM_PSAP_ENTRE_31_55_MMHG_1', 'RB_HIPERTENSAO_ARTERIAL_PULMONAR_SIM_PSAP_MAIOR_55_MMHG_1', 
                      'RB_HIPERTENSAO_ARTERIAL_PULMONAR_SIM_PSAP_MENOR_31_MMHG_1'],
    'disfuncao_ventricular_encam': ['RB_DISFUNCAO_VENTRICULAR_VE_NAO_1', 'RB_DISFUNCAO_VENTRICULAR_VE_SIM_1'],
    'disfuncao_ventricular_encam_2': ['RB_DISFUNCAO_VENTRICULAR_VD_NAO_1',  'RB_DISFUNCAO_VENTRICULAR_VD_SIM_1'],
    'aceita_transfusao': ['RB_ACEITA_TRANSFUSAO_NAO_1', 'RB_ACEITA_TRANSFUSAO_SIM_1'],
    'anticoagulacao': ['RB_ANTICOAGULACAO_DOAC_VALVOPATIAS_1', 'RB_ANTICOAGULACAO_VARFARINA_VALVOPATIAS_1'],
    'assintomatico': ['RB_ASSINTOMATICO_NAO_VALPATIAS_1', 'RB_ASSINTOMATICO_SIM_VALPATIAS_1'],
    'fadiga': ['RB_FADIGA_NAO_VALPATIAS_1', 'RB_FADIGA_SIM_VALPATIAS_1'],
    'palpitacoes': ['RB_PALPITACOES_NAO_VALVOPATIAS_1', 'RB_PALPITACOES_SIM_VALVOPATIAS_1'],
    'carga_sintomas_sincope': ['RB_SINCOPE_NAO_VALVOPATIAS_1', 'RB_SINCOPE_SIM_VALVOPATIAS_1'],
	'angina': ['RB_ANGINA_NAO_VALPATIAS_1',  'RB_ANGINA_SIM_VALPATIAS_1'],
    'ccs': ['RB_ANGINA_SIM_CCS1_SINTOMAS_PRINCIPAL_1', 'RB_ANGINA_SIM_CCS2_SINTOMAS_PRINCIPAL_1', 'RB_ANGINA_SIM_CCS3_SINTOMAS_PRINCIPAL_1', 'RB_ANGINA_SIM_CCS4_SINTOMAS_PRINCIPAL_1'],
    'classe_nyha': ['RB_DISPNEIA_CF_NYHA_I_1', 'RB_DISPNEIA_CF_NYHA_II_1', 'RB_DISPNEIA_CF_NYHA_III_1', 'RB_DISPNEIA_CF_NYHA_IV_1'],
    'cirurgia_proposta': ['PRIMEIRA_CIRURGIA_VALPATIAS_1', 'RB_REOPERACAO_PRIMEIRA_VALPATIAS_1', 'RB_REOPERACAO_SEGUNDA_VALPATIAS_1', 'RB_REOPERACAO_TERCEIRO_VALPATIAS_1', 
                          'RB_REOPERACAO_QUARTA_VALPATIAS_1', 'RB_REOPERACAO_QUINTO_VALPATIAS_1', 'RB_REOPERACAO_SEXTO_VALPATIAS_1'], 
    'tipo_operacao': ['RB_ELETIVA_OPERACAO_1', 'RB_URGENCIA_OPERACAO_1', 'RB_EMERGENCIA_OPERACAO_1', 'RB_SALVAMENTO_OPERACAO_1'],
    'heart_team_encam': ['RB_NAO_DISCUTIDO_HEART_TEAM_1', 'RB_SIM_DISCUTIDO_HEART_TEAM_1'],
    'drc_clcr': ['RB_DOENCA_RENAL_DIALISE_1', 'RB_DOENCA_RENAL_MODERADA_CLCR_ENTRE_50_85_1', 'RB_DOENCA_RENAL_NORMAL_CLCR_MAIOR_85_1', 'RB_DOENCA_RENAL_SEVERA_CLCR_MENOR_50_1'],
    'estado_pr_operat_rio_cr_ti': ['RB_ESTADO_PRE_OPERATORIO_CRITICO_NAO_1', 'RB_ESTADO_PRE_OPERATORIO_CRITICO_SIM_1'], 
    'mobilidade_severa_preju': ['RB_MOBILIDADE_SEVERAMENTE_PREJUDICADA_NAO_1', 'RB_MOBILIDADE_SEVERAMENTE_PREJUDICADA_SIM_1'],
    'arteriopatia_extracardiaca': ['RB_ARTERIOPATIA_EXTRACARDIACA_NAO_1', 'RB_ARTERIOPATIA_EXTRACARDIACA_SIM_1'],
    'iam_menor_90dias': ['RB_INFARTO_MIOCARDIO_MENOR_90_DIAS_NAO_1', 'RB_INFARTO_MIOCARDIO_MENOR_90_DIAS_SIM_1'],
    'dpoc_medicamentos': ['RB_USO_CORTICOIDE_BRONCODILATADOR_LONGA_DATA_NAO_1', 'RB_USO_CORTICOIDE_BRONCODILATADOR_LONGA_DATA_SIM_1'],
    'dpoc': ['RB_DOENCA_PULMONAR_CRONICA_NAO_COMORBIDADES_PRINCIPAIS_1', 'RB_DOENCA_PULMONAR_CRONICA_SIM_COMORBIDADES_PRINCIPAIS_1'],
    'sequela_neurologica': [ 'RB_DATA_EVENTO_MAIS_RECENTE_SEQUELA_NEUROLOGICA_NAO_1', 'RB_DATA_EVENTO_MAIS_RECENTE_SEQUELA_NEUROLOGICA_SIM_1'],
    'avc_ait_previo': ['RB_DOENCA_NEUROLOGICA_PREVIA_AVC_PREVIO_DEFICIT_1', 'RB_DOENCA_NEUROLOGICA_PREVIA_AIT_PREVIO_1', 'RB_DOENCA_NEUROLOGICA_PREVIA_NAO_1', 'RB_DOENCA_NEUROLOGICA_PREVIA_SIM_1'],
    'tabagismo': ['RB_EX_TABAGISTA_1', 'RB_TABAGISMO_NAO_1', 'RB_TABAGISMO_SIM_1'],
    'diabetes_controle': ['RB_DIETA_COMORBIDADES_PRINCIPAIS_1', 'RB_HIPOGLICEMIANTE_ORAL_COMORBIDADES_PRINCIPAIS_1', 'RB_INSULINA_COMORBIDADES_PRINCIPAIS_1'],
    'etilista': ['RB_ETILISTA_ATIVO_COMORBIDADES_PRINCIPAIS_1', 'RB_ETILISTA_NAO_COMORBIDADES_PRINCIPAIS_1', 'RB_EX_ETILISTA_COMORBIDADES_PRINCIPAIS_1'],
    'massa_corporal_critica': ['RB_MASSA_CORPORAL_CRITICA_NAO_1', 'RB_MASSA_CORPORAL_CRITICA_SIM_1'], 
    'avaliacao_corporal': ['RB_MASSA_CORPORAL_CRITICA_CAQUEXIA_IMC_MENOR_18_1', 'RB_MASSA_CORPORAL_CRITICA_OBESIDADE_MORBIDA_IMC_MAIOR_30_1'],
    'endocardite_ativa': ['RB_ENDOCARDITE_ATIVA_NAO_1', 'RB_ENDOCARDITE_ATIVA_SIM_1'],
    'tipo_de_arteriopatia': ['RB_CLAUDICACAO_LIMITANTE_1', 'RB_DOENCA_CAROTIDEA_MAIOR_IGUAL_50_1', 'RB_AMPUTACAO_POR_DAOP_1', 'RB_INTERVENCAO_PLANEJADA_PREVIA_AORTA_ABDOMINAL_MEMBROS_CAROTIDAS_1'],
    'imunossupressao': ['RB_IMUNOSSUPRESSAO_NAO_COMORBIDADES_PRINCIPAIS_1', 'RB_IMUNOSSUPRESSAO_SIM_COMORBIDADES_PRINCIPAIS_1'],
    'tipo_de_imunossupressao': ['RB_DOENCA_COMORBIDADES_PRINCIPAIS_1', 'RB_MEDICACAO_COMORBIDADES_PRINCIPAIS_1'],
    'cancer': ['RB_CANCER_NAO_COMORBIDADES_PRINCIPAIS_1', 'RB_CANCER_SIM_COMORBIDADES_PRINCIPAIS_1'],
    'tratamento_de_cancer': ['RB_TIPO_CANCER_ATIVO_NAO_TRATADO_COMORBIDADES_PRINCIPAIS_1', 'RB_TIPO_CANCER_TRATADO_MAIOR_5_COMORBIDADES_PRINCIPAIS_1', 'RB_TIPO_CANCER_TRATADO_MENOR_5_COMORBIDADES_PRINCIPAIS_1'],
    'doenca_hepatica': ['RB_DOENCA_NAO_HEPATICA_COMORBIDADES_PRINCIPAIS_1', 'RB_DOENCA_SIM_HEPATICA_COMORBIDADES_PRINCIPAIS_1'],
    'cirurgia_anterior': ['RB_CIRURGIA_CARDIACA_PREVIA_NAO_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1', 'RB_CIRURGIA_CARDIACA_PREVIA_SIM_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1'],
    'tipo_de_fa': ['RB_FIBRILACAO_ATRIAL_PAROXISTICA_RITMO_CARDIACO_ATUAL_1', 'RB_FIBRILACAO_ATRIAL_PERMANENTE_RITMO_CARDIACO_ATUAL_1', 'RB_FIBRILACAO_ATRIAL_PERSISTENTE_RITMO_CARDIACO_ATUAL_1'],
    'tipo_mp_trc_cdi': ['RB_MP_DEFINITIVO_RITMO_CARDIACO_ATUAL_1', 'RB_MP_PROVISORIO_RITMO_CARDIACO_ATUAL_1', 'RB_TRC_RITMO_CARDIACO_ATUAL_1', 'RB_CDI_RITMO_CARDIACO_ATUAL_1'],
    'coronaria_exame': ['RB_ANGIOTC_CORONARIAS_ESTUDO_CORONARIAS_1', 'RB_CATETERISMO_CARDIACO_ESTUDO_CORONARIAS_1', 'RB_NAO_REALIZADO_ESTUDO_CORONARIAS_1'],
    'dac_exame':['RB_DOENCA_ARTERIAL_CORONARIANA_DAC_OBSTRUTIVA_NAO_ESTUDO_CORONARIAS_1', 'RB_DOENCA_ARTERIAL_CORONARIANA_DAC_OBSTRUTIVA_SIM_ESTUDO_CORONARIAS_1'],
    'qtde_vasos_acometidos': ['RB_SE_DAC_NUMERO_VASOS_PRINCIPAIS_ACOMETIDOS_MAIOR_70_ESTENOSE_0_ESTUDO_CORONARIAS_1', 'RB_SE_DAC_NUMERO_VASOS_PRINCIPAIS_ACOMETIDOS_MAIOR_70_ESTENOSE_1_ESTUDO_CORONARIAS_1', 
        	'RB_SE_DAC_NUMERO_VASOS_PRINCIPAIS_ACOMETIDOS_MAIOR_70_ESTENOSE_2_ESTUDO_CORONARIAS_1', 'RB_SE_DAC_NUMERO_VASOS_PRINCIPAIS_ACOMETIDOS_MAIOR_70_ESTENOSE_3_ESTUDO_CORONARIAS_1'],
    'tronco_de_coron_ria_esquer': ['RB_TRONCO_CORONARIA_ESQUERDA_MAIOR_50_NAO_ESTUDO_CORONARIAS_1', 'RB_TRONCO_CORONARIA_ESQUERDA_MAIOR_50_SIM_ESTUDO_CORONARIAS_1'],
    'lib_cirurgia':['RB_ODONTOLOGIA_LIBERADO_NAO_OUTROS_EXAMES_1', 'RB_ODONTOLOGIA_LIBERADO_SIM_OUTROS_EXAMES_1'],
    
}

#Atribuindo valores mapeados, binarios
preop_rn = {
    'RB_DM_NAO_1': 0, 'RB_DM_SIM_1': 1,
    'RB_HAS_NAO_1': 0, 'RB_HAS_SIM_1': 1,
	'RB_PS_UTI_ORIGEM_PACIENTE_1': 1, 'RB_ELETICO_ORIGEM_PACIENTE_1': 2,
	'RB_DIAS_AO_SINTOMAS_FICHA_PRE_1': 1, 'RB_MESES_SINTOMAS_FICHA_PRE_1': 2, 'RB_ANOS_SINTOMAS_FICHA_PRE_1': 3,
    'RB_HIPERTENSAO_PULMONAR_NAO_1': 0, 'RB_HIPERTENSAO_PULMONAR_SIM_1': 1, 'RB_HIPERTENSAO_ARTERIAL_PULMONAR_NAO_COMORBIDADES_PRINCIPAIS_1': 0,
    'RB_HIPERTENSAO_ARTERIAL_PULMONAR_SIM_COMORBIDADES_PRINCIPAIS_1': 1,
	'RB_HIPERTENSAO_ARTERIAL_PULMONAR_SIM_PSAP_ENTRE_31_55_MMHG_1': 2, 'RB_HIPERTENSAO_ARTERIAL_PULMONAR_SIM_PSAP_MENOR_31_MMHG_1': 1,
    'RB_HIPERTENSAO_ARTERIAL_PULMONAR_SIM_PSAP_MAIOR_55_MMHG_1': 3, 
	'RB_DISFUNCAO_VENTRICULAR_VE_NAO_1': 0, 'RB_DISFUNCAO_VENTRICULAR_VE_SIM_1': 1,
    'RB_DISFUNCAO_VENTRICULAR_VD_NAO_1': 0, 'RB_DISFUNCAO_VENTRICULAR_VD_SIM_1': 1,
    'RB_ACEITA_TRANSFUSAO_NAO_1': 0, 'RB_ACEITA_TRANSFUSAO_SIM_1': 1,
    'RB_ANTICOAGULACAO_VARFARINA_VALVOPATIAS_1': 1, 'RB_ANTICOAGULACAO_DOAC_VALVOPATIAS_1': 2, 
    'RB_ASSINTOMATICO_NAO_VALPATIAS_1': 0, 'RB_ASSINTOMATICO_SIM_VALPATIAS_1': 1,
    'RB_FADIGA_NAO_VALPATIAS_1': 0, 'RB_FADIGA_SIM_VALPATIAS_1': 1,
    'RB_PALPITACOES_NAO_VALVOPATIAS_1': 0, 'RB_PALPITACOES_SIM_VALVOPATIAS_1': 1, 
	'RB_SINCOPE_NAO_VALVOPATIAS_1': 0, 'RB_SINCOPE_SIM_VALVOPATIAS_1': 1,
    'RB_ANGINA_NAO_VALPATIAS_1': 0,  'RB_ANGINA_SIM_VALPATIAS_1': 1,
    'RB_ANGINA_SIM_CCS1_SINTOMAS_PRINCIPAL_1': 1, 'RB_ANGINA_SIM_CCS2_SINTOMAS_PRINCIPAL_1': 2, 'RB_ANGINA_SIM_CCS3_SINTOMAS_PRINCIPAL_1': 3, 
    'RB_ANGINA_SIM_CCS4_SINTOMAS_PRINCIPAL_1': 4,
    'RB_DISPNEIA_CF_NYHA_I_1': 1, 'RB_DISPNEIA_CF_NYHA_II_1': 2, 'RB_DISPNEIA_CF_NYHA_III_1': 3, 'RB_DISPNEIA_CF_NYHA_IV_1': 4,
    'RB_REOPERACAO_PRIMEIRA_VALPATIAS_1': 1, 'RB_REOPERACAO_SEGUNDA_VALPATIAS_1': 2, 'RB_REOPERACAO_TERCEIRO_VALPATIAS_1': 3,
    'RB_REOPERACAO_QUARTA_VALPATIAS_1': 4, 'RB_REOPERACAO_QUINTO_VALPATIAS_1': 5, 'RB_REOPERACAO_SEXTO_VALPATIAS_1': 6,
    'RB_ELETIVA_OPERACAO_1': 1, 'RB_URGENCIA_OPERACAO_1': 2, 'RB_EMERGENCIA_OPERACAO_1': 3, 'RB_SALVAMENTO_OPERACAO_1': 4,
	'RB_NAO_DISCUTIDO_HEART_TEAM_1': 0, 'RB_SIM_DISCUTIDO_HEART_TEAM_1': 1,
    'RB_DOENCA_RENAL_DIALISE_1': 4, 'RB_DOENCA_RENAL_MODERADA_CLCR_ENTRE_50_85_1': 2, 'RB_DOENCA_RENAL_NORMAL_CLCR_MAIOR_85_1': 1, 
    'RB_DOENCA_RENAL_SEVERA_CLCR_MENOR_50_1': 3,
    'RB_ESTADO_PRE_OPERATORIO_CRITICO_NAO_1': 0, 'RB_ESTADO_PRE_OPERATORIO_CRITICO_SIM_1': 1,
    'RB_MOBILIDADE_SEVERAMENTE_PREJUDICADA_NAO_1': 0, 'RB_MOBILIDADE_SEVERAMENTE_PREJUDICADA_SIM_1': 1,
    'RB_ARTERIOPATIA_EXTRACARDIACA_NAO_1': 0, 'RB_ARTERIOPATIA_EXTRACARDIACA_SIM_1': 1, 
    'RB_INFARTO_MIOCARDIO_MENOR_90_DIAS_NAO_1': 0, 'RB_INFARTO_MIOCARDIO_MENOR_90_DIAS_SIM_1': 1,
    'RB_USO_CORTICOIDE_BRONCODILATADOR_LONGA_DATA_NAO_1': 0, 'RB_USO_CORTICOIDE_BRONCODILATADOR_LONGA_DATA_SIM_1': 1,
    'RB_DOENCA_PULMONAR_CRONICA_NAO_COMORBIDADES_PRINCIPAIS_1': 0, 'RB_DOENCA_PULMONAR_CRONICA_SIM_COMORBIDADES_PRINCIPAIS_1': 1,
    'RB_DATA_EVENTO_MAIS_RECENTE_SEQUELA_NEUROLOGICA_NAO_1': 0, 'RB_DOENCA_NEUROLOGICA_PREVIA_NAO_1': 0, 'RB_DOENCA_NEUROLOGICA_PREVIA_SIM_1': 1,
    'RB_DATA_EVENTO_MAIS_RECENTE_SEQUELA_NEUROLOGICA_SIM_1': 1,
    'RB_EX_TABAGISTA_1': 1, 'RB_TABAGISMO_NAO_1': 0, 'RB_TABAGISMO_SIM_1': 2,
	'RB_DIETA_COMORBIDADES_PRINCIPAIS_1': 1, 'RB_HIPOGLICEMIANTE_ORAL_COMORBIDADES_PRINCIPAIS_1': 2, 'RB_INSULINA_COMORBIDADES_PRINCIPAIS_1': 3,
    'RB_ETILISTA_ATIVO_COMORBIDADES_PRINCIPAIS_1': 2, 'RB_ETILISTA_NAO_COMORBIDADES_PRINCIPAIS_1': 0, 'RB_EX_ETILISTA_COMORBIDADES_PRINCIPAIS_1': 1,
    'RB_MASSA_CORPORAL_CRITICA_CAQUEXIA_IMC_MENOR_18_1': 2, 'RB_MASSA_CORPORAL_CRITICA_NAO_1': 0, 'RB_MASSA_CORPORAL_CRITICA_SIM_1': 1,
    'RB_MASSA_CORPORAL_CRITICA_OBESIDADE_MORBIDA_IMC_MAIOR_30_1': 1,  
    'RB_ENDOCARDITE_ATIVA_NAO_1': 0, 'RB_ENDOCARDITE_ATIVA_SIM_1': 1,
    'RB_CLAUDICACAO_LIMITANTE_1': 1, 'RB_DOENCA_CAROTIDEA_MAIOR_IGUAL_50_1': 2, 'RB_AMPUTACAO_POR_DAOP_1': 3, 
    'RB_INTERVENCAO_PLANEJADA_PREVIA_AORTA_ABDOMINAL_MEMBROS_CAROTIDAS_1': 4,
    'RB_IMUNOSSUPRESSAO_NAO_COMORBIDADES_PRINCIPAIS_1': 0, 'RB_IMUNOSSUPRESSAO_SIM_COMORBIDADES_PRINCIPAIS_1': 1,
    'RB_DOENCA_COMORBIDADES_PRINCIPAIS_1': 1, 'RB_MEDICACAO_COMORBIDADES_PRINCIPAIS_1': 2,
    'RB_TIPO_CANCER_ATIVO_NAO_TRATADO_COMORBIDADES_PRINCIPAIS_1': 1, 'RB_TIPO_CANCER_TRATADO_MAIOR_5_COMORBIDADES_PRINCIPAIS_1': 3, 
    'RB_TIPO_CANCER_TRATADO_MENOR_5_COMORBIDADES_PRINCIPAIS_1': 2,
    'RB_CANCER_NAO_COMORBIDADES_PRINCIPAIS_1': 0, 'RB_CANCER_SIM_COMORBIDADES_PRINCIPAIS_1': 1,
    'RB_DOENCA_NAO_HEPATICA_COMORBIDADES_PRINCIPAIS_1': 0, 'RB_DOENCA_SIM_HEPATICA_COMORBIDADES_PRINCIPAIS_1': 1,
    'RB_CIRURGIA_CARDIACA_PREVIA_NAO_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1': 0, 'RB_CIRURGIA_CARDIACA_PREVIA_SIM_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1': 1,
    'RB_FIBRILACAO_ATRIAL_PAROXISTICA_RITMO_CARDIACO_ATUAL_1': 1, 'RB_FIBRILACAO_ATRIAL_PERMANENTE_RITMO_CARDIACO_ATUAL_1': 3, 
    'RB_FIBRILACAO_ATRIAL_PERSISTENTE_RITMO_CARDIACO_ATUAL_1': 2,
    'RB_MP_DEFINITIVO_RITMO_CARDIACO_ATUAL_1': 2, 'RB_MP_PROVISORIO_RITMO_CARDIACO_ATUAL_1': 1, 'RB_TRC_RITMO_CARDIACO_ATUAL_1': 3,
    'RB_CDI_RITMO_CARDIACO_ATUAL_1': 4,
    'RB_ANGIOTC_CORONARIAS_ESTUDO_CORONARIAS_1': 2, 'RB_CATETERISMO_CARDIACO_ESTUDO_CORONARIAS_1': 1, 'RB_NAO_REALIZADO_ESTUDO_CORONARIAS_1': 0,
    'RB_DOENCA_ARTERIAL_CORONARIANA_DAC_OBSTRUTIVA_NAO_ESTUDO_CORONARIAS_1': 0, 'RB_DOENCA_ARTERIAL_CORONARIANA_DAC_OBSTRUTIVA_SIM_ESTUDO_CORONARIAS_1': 1,
    'RB_SE_DAC_NUMERO_VASOS_PRINCIPAIS_ACOMETIDOS_MAIOR_70_ESTENOSE_0_ESTUDO_CORONARIAS_1': 0, 
    'RB_SE_DAC_NUMERO_VASOS_PRINCIPAIS_ACOMETIDOS_MAIOR_70_ESTENOSE_1_ESTUDO_CORONARIAS_1': 1, 
    'RB_SE_DAC_NUMERO_VASOS_PRINCIPAIS_ACOMETIDOS_MAIOR_70_ESTENOSE_2_ESTUDO_CORONARIAS_1': 2, 
    'RB_SE_DAC_NUMERO_VASOS_PRINCIPAIS_ACOMETIDOS_MAIOR_70_ESTENOSE_3_ESTUDO_CORONARIAS_1': 3,
	'RB_TRONCO_CORONARIA_ESQUERDA_MAIOR_50_NAO_ESTUDO_CORONARIAS_1': 0, 'RB_TRONCO_CORONARIA_ESQUERDA_MAIOR_50_SIM_ESTUDO_CORONARIAS_1': 1,
    'RB_ODONTOLOGIA_LIBERADO_NAO_OUTROS_EXAMES_1': 0, 'RB_ODONTOLOGIA_LIBERADO_SIM_OUTROS_EXAMES_1': 1,
   
}

#Mapeamento direto, trocando nomes de colunas
preop_maps = {
    'CD_ATENDIMENTO': 						 'cd_atendimento',
    'CD_PACIENTE':							 'record_id',
    
	'DS_DURACAO_SINTOMAS_FICHA_PRE_1': 								'tempo_sintomas_duracao',
	'RB_HIPERTENSAO_PULMONAR_VALOR_PSAP_1': 						'resultado_eco_psap',
    'DS_AORTA_ASCENDENTE_PARAMETROS_ECOCARDIOGRAFICOS_1': 			'aorta_ascendente',
	'DS_RAIZ_AORTA_PARAMETRO_ECOCARDIOGRADICO_1': 					'raiz_aorta',
    'DT_DATA_ECO_1': 												'data_do_eco',
    'DS_ALTURA_MAPAR_1': 											'altura',
    'DS_PESO_MAPA_1': 												'peso',
    'DS_EUROSCORE_1': 												'euroscore_ii',
	'RB_DISFUNCAO_VENTRICULAR_FEVE_1':								'feve_encam',  
    'RB_DISFUNCAO_VENTRICULAR_TAPSE_1':								'tapse_encam',
    'RB_DISFUNCAO_VENTRICULAR_FAC_1': 								'fac_encam',
    'DS_CARGA_TABAGICA_COMORBIDADES_PRINCIPAIS_1': 					'carga_tabagica',
    'DT_DATA_EVENTO_MAIS_RECENTE_1': 								'data_avc_ait',
    'DT_DATA_DIAGNOSTICO_ENDOCARDITE_ATIVA_1': 						'data_endocardite_ativa',
	'RB_CANCER_TIPO_CANCER_COMORBIDADES_PRINCIPAIS_1':  			'tipo_de_cancer',
    'RB_CIRURGIA_AORTA_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1': 		'tipo_de_cirurgia_anterior___2',
    'RB_CIRURGIA_VALVAR_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1': 	'tipo_de_cirurgia_anterior___3',
    'RB_REVASCULARIZACAO_MIOCARDICA_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1':	'tipo_de_cirurgia_anterior___1',
    'RB_OUTRA_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1':				'tipo_de_cirurgia_anterior___4',
    'RB_SINUSAL_RITMO_CARDIACO_ATUAL_1':  							'tipo_arritmia___7',
    'RB_FLUTTER_ATRIAL_RITMO_CARDIACO_ATUAL_1':  					'tipo_arritmia___2',
    'RB_BLOQUEIO_ATRIOVENTRICULAR_BAV_ALTO_GRAU_RITMO_CARDIACO_ATUAL_1':  		'tipo_arritmia___6',
    'DT_DATA_ESTUDO_CORONARIAS_1': 									'data_coronaria_exame',
    'DT_DATA_ODONTOLOGIA_LIBERADO_OUTROS_EXAMES_1':  				'dt_libera_odonto',
	'RB_ANO_ULTIMA_CIRURGIA_CARDIACA_HISTORICO_CARDIACO_CIRURGICO_PREVIO_1':	 'dt_prev_cir',
	'RB_EAO_VALPATIAS_1':											'diagnostico_principal___1', 
    'RB_IAO_VALVOPATIAS_1': 										'diagnostico_principal___2',
    'RB_EM_VALVOPATIAS_1':											'diagnostico_principal___3', 
	'RB_IM_VALVOPATIAS_1':											'diagnostico_principal___4', 
	'RB_DOENCA_TRICUSPIDE_VALVOPATIAS_1':							'diagnostico_principal___5', 
	'RB_ANEURISMA_AORTA_VALVOPATIAS_1':								'diagnostico_principal___6', 
	'RB_DISFUNCAO_PROTESE_VALVAR_VALVOPATIAS_1':					'diagnostico_principal___7', 
	'RB_ENDOCARDITE_VALVOPATIAS_1':									'diagnostico_principal___8', 
	'RB_TROMBOSE_DIAGNOSTICO_PRINCIPAL_1':							'diagnostico_principal___9',
	'RB_AORTICA_VALVOPATIAS_1':  									'valvula_afetada___1',
	'RB_MITRAL_VALVOPATIAS_1':  									'valvula_afetada___2',
	'RB_TRICUSPIDE_VALVOPATIAS_1':  								'valvula_afetada___3',

	# MITRAL - NATIVA
	'RB_NATIVA_VALVA_MITRAL_1':										'valvula_nativa_2',
	'RB_SEM_LESAO_DISCRETA_1':										'lesao_valvar_disc_2',
	'RB_DISFUNCAO_ESTENOSE_MODERADA_1':								'estenose_moderada_2',
	'RB_DISFUNCAO_ESTENOSE_IMPORTANTE_1':							'estenose_importante_2',
	'RB_DISFUNCAO_INSUFICIENCIA_MODERADA_1':						'insuficiencia_moderada_2',
	'RB_DISFUNCAO_INSUFICIENCIA_IMPORTANTE_1':						'insuficiencia_importante_2',
	'DS_GRADIENTES_MAX_VALVA_MITRAL_NATIVA_1':						'mi_nativa_gd_max',
	'DS_GRADIENTES_MEDIO_1':										'mi_nativa_gd_med',
	'DS_AREA_VALVAR_1':												'area_valvar',
	'RB_ETIOLOGIA_REUMATICA_1':										'etiologia_valva_mitral___1',
	'RB_ETIOLOGIA_CALCIFICA_1':										'etiologia_valva_mitral___2',
	'RB_ETIOLOGIA_FUNCIONAL_1':										'etiologia_valva_mitral___3',
	'RB_ETIOLOGIA_FIBROELASTICA_PROLAPSO_BARLOW_1':					'etiologia_valva_mitral___4',
	'RB_ETIOLOGIA_ENDOCARDITE_1':									'etiologia_valva_mitral___5',

	# MITRAL - PROTESE
	'RB_PROTESE_BIOLOGICA_1':										'protese_biologica_2',
	'RB_PROTESE_MECANICA_1':										'protese_mecanica_2',
	'RB_NORMOFUNCIONANTE_1':										'lesao_valvar_normo_2',
	'RB_DISFUNCAO_MODERADA_VALVA_MITRAL_1':							'disfuncao_moderada_2',
	'RB_DISFUNCAO_IMPORTANTE_VALVA_MITRAL_1':						'disfuncao_importante_2',
	'DS_GRADIENTES_MAX_VALVA_MITRAL_BIOLOGICA_MECANICA_1':			'mi_protese_gd_max',
	'DS_GRADIENTES_MEDIO_2':										'mi_protese_gd_med',
	'DS_AREA_VALVAR_2':												'area_valvar_2',
	'RB_ETIOLOGIA_ESTRUTURAL_ESTENOSE_1':							'etio_estrut_protese_mi___1',
	'RB_ETIOLOGIA_ESTRUTURAL_INSUFICIENCIA_1':						'etio_estrut_protese_mi___2',
	'RB_ETIOLOGIA_ESTRUTURAL_LEAK_1':								'etio_estrutural_mitral_2___1',
	'RB_ETIOLOGIA_ESTRUTURAL_MISMATCH_1':							'etio_estrutural_mitral_2___2',
	'RB_ETIOLOGIA_ESTRUTURAL_PANNUS_1':								'etio_estrutural_mitral_2___3',
	'RB_ETIOLOGIA_ESTRUTURAL_ENDOCARDITE_1':						'etio_estrutural_mitral_2___4',
	'RB_ETIOLOGIA_ESTRUTURAL_TROMBOSE_1':							'etio_estrutural_mitral_2___5',

	# AORTICA - NATIVA
	'RB_NATIVA_VALVA_AORTICA_1':										'valvula_nativa_1',
	'RB_SEM_LESAO_DISCRETA_MECANICA_VALVA_AORTICA_1':					'lesao_valvar_disc_1',
	'RB_DISFUNCAO_ESTENOSE_MODERADA_VALVA_AORTICA_1':					'estenose_moderada_1',
	'RB_DISFUNCAO_ESTENOSE_IMPORTANTE_VALVA_AORTICA_1':					'estenose_importante_1',
	'RB_DISFUNCAO_INSUFICIENCIA_MODERADA_VALVA_AORTICA_1':				'insuficiencia_moderada_1',
	'RB_DISFUNCAO_INSUFICIENCIA_IMPORTANTE_VALVA_AORTICA_1':			'insuficiencia_importante_1',
	'RB_GRADIENTES_MAX_VALVA_AORTICA_1':								'ao_nativa_gd_max',
	'RB_GRADIENTES_MEDIO_VALVA_AORTICA_1':								'ao_nativa_gd_med',
	'RB_AREA_VALVAR_VALVA_AORTICA_1':									'area_valvar_3',
	'RB_ETIOLOGIA_ANEURISMA_DISSECCAO_VALVA_AORTICA_1':					'etiologia_valva_aortica___1',
	'RB_ETIOLOGIA_BIVALVULAR_VALVA_AORTICA_1':							'etiologia_valva_aortica___2',
	'RB_ETIOLOGIA_REUMATICA_VALVA_AORTICA_1':							'etiologia_valva_aortica___3',
	'RB_ETIOLOGIA_CALCIFICA_VALVA_AORTICA_1':							'etiologia_valva_aortica___4',
	'RB_ETIOLOGIA_ENDOCARDITE_VALVA_AORTICA_1':							'etiologia_valva_aortica___5',

	# AORTICA - PROTESE
	'RB_PROTESE_BIOLOGICA_VALVA_AORTICA_1':								'protese_biologica_1',
	'RB_PROTESE_MECANICA_VALVA_AORTICA_1':								'protese_mecanica_1',
	'DS_NORMOFUNCIONANTE_VALVA_AORTICA_1':								'lesao_valvar_normo_1',
	'RB_DISFUNCAO_MODERADA_VALVA_AORTICA_1':							'disfuncao_moderada_1',
	'RB_DISFUNCAO_IMPORTANTE_VALVA_AORTICA_1':							'disfuncao_importante_1',
	'RB_GRADIENTES_MAX_VALVA_AORTICA_2':								'ao_protese_gd_max',
	'RB_GRADIENTES_MEDIO_VALVA_AORTICA_2':								'ao_protese_gd_med',
	'RB_AREA_VALVAR_VALVA_AORTICA_2':									'area_valvar_4',
    'RB_ETIOLOGIA_ESTRUTURAL_ESTONOSE_VALVA_AORTICA_1':					'etio_estrut_protese_ao___1', 
	'RB_ETIOLOGIA_ESTRUTURAL_INSUFICIENCIA_VALVA_AORTICA_1':			'etio_estrut_protese_ao___2', 
	'RB_ETIOLOGIA_NAO_ESTRUTURAL_LEAK_VALVA_AORTICA_1':					'etio_estrutural_aortica_2___1',
	'RB_ETIOLOGIA_NAO_ESTRUTURAL_MISMATCH_VALVA_AORTICA_1':				'etio_estrutural_aortica_2___2',
	'RB_ETIOLOGIA_NAO_ESTRUTURAL_PANNUS_VALVA_AORTICA_1':				'etio_estrutural_aortica_2___3',
	'RB_ETIOLOGIA_NAO_ESTRUTURAL_ENDOCARDITE_VALVA_AORTICA_1':			'etio_estrutural_aortica_2___4',
	'RB_ETIOLOGIA_NAO_ESTRUTURAL_TROMBOSE_VALVA_AORTICA_1':				'etio_estrutural_aortica_2___5',

	# TRICUSPIDE - NATIVA
	'RB_NATIVA_VALVA_TRICUSPIDE_1':											'valvula_nativa_3',
	'RB_SEM_LESAO_DISCRETA_VALVA_TRICUSPIDE_1':								'lesao_valvar_disc_3',
	'RB_ESTENOSE_MODERADA_VALVA_TRICUSPIDE_1':								'estenose_moderada_3',
	'RB_ESTENOSE_IMPORTANTE_1':												'estenose_importante_3',
	'RB_INSUFICIENCIA_MODERADA_VALVA_TRICUSPIDE_1':							'insuficiencia_moderada_3',
	'RB_INSUFICIENCIA_IMPORTANTE_1':										'insuficiencia_importante_3',
	'RB_ANEL_VALVA_TRICUSPIDE_1':											'anel_valva_tricuspide',
	'RB_PRIMARIA_ETIOLOGIA_NATIVA_TRICUSPIDE_1':							'etiologia_valva_tricuspide___1',
	'RB_FUNCIONAL_ETIOLOGIA_NATIVA_TRICUSPIDE_1':							'etiologia_valva_tricuspide___2',
	'RB_ASSOCIADA_DCEI_ETIOLOGIA_NATIVA_TRICUSPIDE_1':						'etiologia_valva_tricuspide___3',
	'RB_ENDOCARDITE_ETIOLOGIA_NATIVA_TRICUSPIDE_1':							'etiologia_valva_tricuspide___4',

	# TRICUSPIDE - PROTESE
	'RB_PROTESE_BIOLOGICA_VALVA_TRICUSPIDE_1':								'protese_biologica_3',
	'RB_PROTESE_MECANICA_VALVA_TRICUSPIDE_1':								'protese_mecanica_3',
	'RB_NORMOFUNCIONANTE_BIOLOGICA_MECANICA_VALVA_TRICUSPIDE_1':			'lesao_valvar_normo_3',
	'RB_DISFUNCAO_MODERADA_BIOLOGICA_MECANICA_VALVA_TRICUSPIDE_1':			'disfuncao_moderada_3',
	'RB_DISFUNCAO_IMPORTANTE_BIOLOGICA_MECANICA_VALVA_TRICUSPIDE_1':		'disfuncao_importante_3',
	'DS_AREA_VALVAR_3':														'area_valvar_5',
	'RB_ESTENOSE_ETIOLOGIA_VALVA_TRICUSPIDE_1':								'etio_estrut_protese_tri___1',
	'RB_INSUFICIENCIA_ETIOLOGIA_VALVA_TRICUSPIDE_1':						'etio_estrut_protese_tri___2',
	'RB_LEAK_ETIOLOGIA_VALVA_TRICUSPIDE_1':									'etio_estrutural_tricus_2___1',
	'RB_MISMATCH_ETIOLOGIA_VALVA_TRICUSPIDE_1':								'etio_estrutural_tricus_2___2',
	'RB_PANNUS_ETIOLOGIA_VALVA_TRICUSPIDE_1':								'etio_estrutural_tricus_2___3',
	'RB_ENDECARDITE_ETIOLOGIA_VALVA_TRICUSPIDE_1':							'etio_estrutural_tricus_2___4',
	'RB_TROMBOSE_ETIOLOGIA_VALVA_TRICUSPIDE_1':								'etio_estrutural_tricus_2___5',
    'RB_TV_AORTICA_INTERVENCAO_CIRURGICA_1':								'plano_cirurgico_valvar___1',
    'RB_TV_MITRAL_INTERVENCAO_CIRURGICA_1':                                 'plano_cirurgico_valvar___2',							
    'RB_TV_TRICUSPIDE_INTERVENCAO_CIRURGICA_1':                             'plano_cirurgico_valvar___3',						
    'RB_PLASTIA_AORTICA_INTERVENCAO_CIRURGICA_1':                           'plano_cirurgico_valvar___4',						
    'RB_PLASTIA_MITRAL_INTERVENCAO_CIRURGICA_1':                            'plano_cirurgico_valvar___5',						
    'RB_PLASTIA_TRICUSPIDE_INTERVENCAO_CIRURGICA_1':                        'plano_cirurgico_valvar___6',
    'RB_REVASCULARIZACAO_MIOCARDICA_SIM_CIRURGIA_ASSOCIAD_1':				'plano_cirurgico_associado___1',
    'RB_CORRECAO_ANEURISMA_AORTA_SIM_CIRURGIA_ASSOCIADA_1':				    'plano_cirurgico_associado___2',
    'RB_ABLACAO_FA_FLUTTER_SIM_CIRURGIA_ASSOCIADA_1':                       'plano_cirurgico_associado___3',
    'RB_FECHAMENTO_APENDICE_ATRIAL_SIM_CIRURGIA_ASSOCIADA_1':               'plano_cirurgico_associado___4',
    'RB_FECHAMENTO_CIV_SIM_CIRURGIA_ASSOCIADA_1':                           'plano_cirurgico_associado___5',
    'RB_MIECTOMIA_SIM_CIRURGIA_ASSOCIADA_1':                                'plano_cirurgico_associado___6',
    'RB_TROMBECTOMIA_SIM_CIRURGIA_ASSOCIADA_1':                             'plano_cirurgico_associado___7',
    'RB_MECANICA_SE_PROTESE_QUAL_TIPO_INTERVENCAO_CIRURGICA_1':             'plano_cirurgico_protese___1',
    'RB_BIOLOGICA_SE_PROTESE_QUAL_TIPO_INTERVENCAO_CIRURGICA_1':            'plano_cirurgico_protese___2',
    
}

#Colunas para excluir
preop_cols_excluir = {
    'RB_DISFUNCAO_VENTRICULAR_TAPSE_N_A_1', 'RB_DISFUNCAO_VENTRICULAR_FAC_N_A_1',
    'RB_ANTICOAGULACAO_NAO_VALVOPATIAS_1',
    'DS_RESIDENTE_1', 'DS_CASO_DISCUTIDO_STAFF_1', 'RB_PROTOCOLO_ESTUDO_SIM_DESCRICAO_1',
	'RB_PROTOCOLO_ESTUDO_SIM_1', 'RB_PROTOCOLO_ESTUDO_NAO_1',
    'RB_REVASCULARIZACAO_MIOCARDICA_NAO_CIRURGIA_ASSOCIAD_1',
    'RB_CORRECAO_ANEURISMA_AORTA_NAO_CIRURGIA_ASSOCIADA_1',		
    'RB_ABLACAO_FA_FLUTTER_NAO_CIRURGIA_ASSOCIADA_1',					
    'RB_FECHAMENTO_APENDICE_ATRIAL_NAO_CIRURGIA_ASSOCIADA_1',			
    'RB_FECHAMENTO_CIV_NAO_CIRURGIA_ASSOCIADA_1',						
    'RB_MIECTOMIA_NAO_CIRURGIA_ASSOCIADA_1',							
    'RB_TROMBECTOMIA_NAO_CIRURGIA_ASSOCIADA_1',
	'DS_OBS_SE_PROTESE_QUAL_TIPO_INTERVENCAO_CIRURGICA_1',
    
}


# 'cirurgia_proposta': ['PRIMEIRA_CIRURGIA_VALPATIAS_1',
# 'PRIMEIRA_CIRURGIA_VALPATIAS_1': 1, 
# 'RB_DOENCA_NEUROLOGICA_PREVIA_AVC_PREVIO_DEFICIT_1', 'RB_DOENCA_NEUROLOGICA_PREVIA_AIT_PREVIO_1',


# --------------------------------------
# Dicionário Mapeado Ficha 1172 - Geronto
# --------------------------------------

#Organiza as colunas mapeadas
geronto_ls = {
 
# --- LF ---
'lf_perda_peso':['PERDA_PESO_NAO_INTENCIONAL_NAO_1', 'PERDA_PESO_NAO_INTENCIONAL_SIM_1',],
'lf_fadiga':[ 'FADIGA_EXAUSTAO_AUTORREFERIDA_NAO_1', 'FADIGA_EXAUSTAO_AUTORREFERIDA_SIM_1',],
'lf_dim_forca':['FORCA_MUSCULAR_REDUZIDA_NAO_1', 'FORCA_MUSCULAR_REDUZIDA_SIM_1',],
'lf_lentidao_marcha':['VELOCIDADE_MARCHA_LENTA_NAO_1', 'VELOCIDADE_MARCHA_LENTA_SIM_1',],
'lf_baixa_ativ_fisica':['BAIXO_NIVEL_ATIVIDADE_FISICA_NAO_1', 'BAIXO_NIVEL_ATIVIDADE_FISICA_SIM_1',],

# --- BARTHEL ---
'barthel_alimentacao':['INDEPENDENTE_ALIMENTACAO_1', 'PRECISA_AJUDA_ALIMENTACAO_1', 'INCAPACITADO_ALIMENTACAO_1',],
'barthel_banho':['INDEPENDENTE_BANHO_1', 'DEPENDENTE_BANHO_1',],
'barthel_hig_pessoal':['INDEPENDENTE_ATIVIDADES_ROTINEIRAS_1', 'PRECISA_AJUDA_HIGIENE_PESSOAL_ATIVIDADE_ROTINEIRAS_1',],
'barthel_vestir':['INDEPENDENTE_VESTIR_SE_1', 'PRECISA_AJUDA_VESTIR_SE_1', 'DEPENDENTE_VESTIR_SE_1',],
'barthel_intestinos':['INCONTINENTE_INTESTINO_1', 'ACIDENTE_OCASIONAL_INTESTINO_1', 'CONTINENTE_INTESTINO_1',],
'barthel_bexiga':['INCONTINENTE_CATETERIZADIZADO_INCAPAZ_MANEJO_SISTEMA_URINARIO_1', 'ACIDENTE_OCASIONAL_SISTEMA_URINARIO_1', 'CONTINENTE_SISTEMA_URINARIO_1',],
'barthel_uso_vaso':['INDEPENDENTE_USO_BANHEIRO_1', 'PRECISA_ALGUMA_AJUDA_PARCIAL_USO_BANHEIRO_1', 'DEPENDENTE_USO_BANHEIRO_1',],
'barthel_transfer':['INDEPENDENTE_TRANSFERENCIA_1', 'POUCA_AJUDA_TRANSFERENCIA_1', 'MUITA_AJUDA_TRANSFERENCIA_1', 'INCAPACITADO_TRANSFERENCIA_1',],
'barthel_mobilidade':['IMOVEL_MOBILIDADE_1', 'CADEIRAS_RODAS_INDEPENDENTE_MOBILIDADE_1', 'CAMINHA_AJUDA_PESSOA_MOBILIDADE_1', 'INDEPENDENTE_MOBILIDADE_1',],
'barthel_escadas':['INDEPENDENTE_ESCADAS_1', 'PRECISA_AJUDA_ESCADAS_1', 'INCAPACITADO_ESCADAS_1',],



# --- LAWTON ---
'lawton_telefone':['USAR_TELEFONE_NAO_AIVD_1',  'USAR_TELEFONE_SIM_AIVD_1',],
'lawton_compras':['FAZER_COMPRAS_NAO_AIVD_1',  'FAZER_COMPRAS_SIM_AIVD_1',],
'lawton_refeicoes':['PREPARAR_REFEICOES_NAO_AIVD_1',  'PREPARAR_REFEICOES_SIM_AIVD_1',],
'lawton_casa':['CUIDAR_CASA_NAO_AIVD_1',  'CUIDAR_CASA_SIM_AIVD_1',],
'lawton_lavar_roupa':['LAVAR_ROUPA_NAO_AIVD_1',  'LAVAR_ROUPA_SIM_AIVD_1',],
'lawton_transporte':['USAR_MEIOS_TRANSPORTE_NAO_AIVD_1',  'USAR_MEIOS_TRANSPORTE_SIM_AIVD_1',],
'lawton_medicamentos':['RESPONSABILIDADE_MEDICAMENTOS_NAO_AIVD_1',  'RESPONSABILIDADE_MEDICAMENTOS_SIM_AIVD_1',],
'lawton_financas':['GERENCIAR_FINANCAS_NAO_AIVD_1',  'GERENCIAR_FINANCAS_SIM_AIVD_1',],


# --- SARCF ---
'sarcf_forca':['DIFICULDADE_LEVANTAR_CARREGAR_ALGUMA_SARC_F_1',  'DIFICULDADE_LEVANTAR_CARREGAR_MUITA_SARC_F_1',
            'DIFICULDADE_LEVANTAR_CARREGAR_NENHUMA_SARC_F_1',],
'sarcf_caminho':['CAMINHAR_DENTRO_COMODO_ALGUMA_SARC_F_1',  'CAMINHAR_DENTRO_COMODO_MUITA_SARC_F_1',
            'CAMINHAR_DENTRO_COMODO_NENHUMA_SARC_F_1',],
'sarcf_levanta_cadeira':['LEVANTAR_DE_UMA_CADEIRA_ALGUMA_SARC_F_1',  'LEVANTAR_DE_UMA_CADEIRA_MUITA_SARC_F_1',
            'LEVANTAR_DE_UMA_CADEIRA_NENHUMA_SARC_F_1',],
'sarcf_escadas':['SUBIR_LANCE_10_DEGRAUS_ALGUMA_SARC_F_1',  'SUBIR_LANCE_10_DEGRAUS_MUITA_SARC_F_1',
			'SUBIR_LANCE_10_DEGRAUS_NENHUMA_SARC_F_1',],
'sarcf_queda':['QUANTAS_VEZES_CAIU_ULTIMO_ANO_ALGUMA_SARC_F_1',  'QUANTAS_VEZES_CAIU_ULTIMO_ANO_MUITA_SARC_F_1',
			'QUANTAS_VEZES_CAIU_ULTIMO_ANO_NENHUMA_SARC_F_1',],


# --- APGAR FAMILIAR ---
'apgar_ajuda':['SATIFEITO_AJUDA_RECEBE_SUA_FAMILIA_QUANDO_ALGUM_PROBLEMA_ALGUMAS_VEZES_APGAR_FAMILIAR_1',
 	'SATIFEITO_AJUDA_RECEBE_SUA_FAMILIA_QUANDO_ALGUM_PROBLEMA_QUASE_SEMPRE_APGAR_FAMILIAR_1',
 	'SATIFEITO_AJUDA_RECEBE_SUA_FAMILIA_QUANDO_ALGUM_PROBLEMA_RARAMENTE_APGAR_FAMILIAR_1',],
'apgar_discute_problemas':['SATIFEITO_FORMA_COMO_SUA_FAMILIA_CONVERSA_SOBRE_PROBLEMAS_ALGUMAS_VEZES_APGAR_FAMILIAR_1',
 	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_CONVERSA_SOBRE_PROBLEMAS_QUASE_SEMPRE_APGAR_FAMILIAR_1',
 	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_CONVERSA_SOBRE_PROBLEMAS_RARAMENTE_APGAR_FAMILIAR_1',],
'apgar_apoia_desejos':['SATIFEITO_FORMA_COMO_SUA_FAMILIA_ACEITA_SUES_DESEJOS_ALGUMAS_VEZES_APGAR_FAMILIAR_1',
 	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_ACEITA_SUES_DESEJOS_QUASE_SEMPRE_APGAR_FAMILIAR_1',
 	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_ACEITA_SUES_DESEJOS_RARAMENTE_APGAR_FAMILIAR_1',],
'apgar_responde_emocoes':['SATIFEITO_FORMA_COMO_PODE_CONTAR_FAMILIA_SITUACOES_DIFICEIS_ALGUMAS_VEZES_APGAR_FAMILIAR_1',
 	'SATIFEITO_FORMA_COMO_PODE_CONTAR_FAMILIA_SITUACOES_DIFICEIS_QUASE_SEMPRE_APGAR_FAMILIAR_1',
 	'SATIFEITO_FORMA_COMO_PODE_CONTAR_FAMILIA_SITUACOES_DIFICEIS_RARAMENTE_APGAR_FAMILIAR_1',],
'apgar_tempo_juntos':['SATIFEITO_COM_TEMPO_FAMILIA_JUNTOS_ALGUMAS_VEZES_APGAR_FAMILIAR_1',
 	'SATIFEITO_COM_TEMPO_FAMILIA_JUNTOS_QUASE_SEMPRE_APGAR_FAMILIAR_1',
 	'SATIFEITO_COM_TEMPO_FAMILIA_JUNTOS_RARAMENTE_APGAR_FAMILIAR_1',],


# --- GDS-15 ---
'gds15_1_satisfeito_vida':['ESTA_SATISFEIRO_COM_SUA_VIDA_NAO_GDS_15_1',  'ESTA_SATISFEIRO_COM_SUA_VIDA_SIM_GDS_15_1',],
'gds15_2_abandono_atividade':['INTERROMPEU_MUITA_ATIVIDADES_NAO_GDS_15_1',  'INTERROMPEU_MUITA_ATIVIDADES_SIM_GDS_15_1',],
'gds15_3_vida_vazia':['ACHA_SUA_VIDA_VAZIA_NAO_GDS_15_1',  'ACHA_SUA_VIDA_VAZIA_SIM_GDS_15_1',],
'gds15_4_aborrecido_freq':['ABORRECE_SE_COM_FREQUENCIA_NAO_GDS_15_1',  'ABORRECE_SE_COM_FREQUENCIA_SIM_GDS_15_1',],
'gds15_5_animado_humor':['SENTE_SE_BEM_COM_VIDA_MAIOR_PARTE_TEMPO_NAO_GDS_15_1',  'SENTE_SE_BEM_COM_VIDA_MAIOR_PARTE_TEMPO_SIM_GDS_15_1',],
'gds15_6_medo_ruim':['TEME_QUE_ALGO_RUIM_LHE_ACONTECA_NAO_GDS_15_1',  'TEME_QUE_ALGO_RUIM_LHE_ACONTECA_SIM_GDS_15_1',],
'gds15_7_feliz_todo':['SENTE_SE_ALEGRE_MAIOR_PARTE_TEMPO_NAO_GDS_15_1',  'SENTE_SE_ALEGRE_MAIOR_PARTE_TEMPO_SIM_GDS_15_1',],
'gds15_8_desamparado_freq':['SENTE_SE_DESAMPARADO_COM_FREQUENCIA_NAO_GDS_15_1',  'SENTE_SE_DESAMPARADO_COM_FREQUENCIA_SIM_GDS_15_1',],
'gds15_9_prefere_casa':['PREFERE_FICAR_CASA_SAIR_FAZER_COISAS_NOVAS_NAO_GDS_15_1',  'PREFERE_FICAR_CASA_SAIR_FAZER_COISAS_NOVAS_SIM_GDS_15_1',],
'gds15_10_problema_memoria':['ACHA_MAIS_PROBLEMAS_MEMORIA_OUTRAS_PESSOAS_NAO_GDS_15_1',  'ACHA_MAIS_PROBLEMAS_MEMORIA_OUTRAS_PESSOAS_SIM_GDS_15_1',],
'gds15_11_maravilha_vivo':['ACHA_MARAVILHOSO_VIVO_NAO_GDS_15_1',  'ACHA_MARAVILHOSO_VIVO_SIM_GDS_15_1',],
'gds15_12_inutil_semvalor':['SENTE_SE_INUTIL_NAO_GDS_15_1',  'SENTE_SE_INUTIL_SIM_GDS_15_1',],
'gds15_13_energizado':['SENTE_SE_CHEIO_DE_ENERGIA_NAO_GDS_15_1',  'SENTE_SE_CHEIO_DE_ENERGIA_SIM_GDS_15_1',],
'gds15_14_sem_esperanca':['SENTE_SE_SEM_ESPERANCA_NAO_GDS_15_1',  'SENTE_SE_SEM_ESPERANCA_SIM_GDS_15_1',],
'gds15_15_pessoas_melhores':['ACHA_OUTROS_MAIS_SORTE_VOCE_NAO_GDS_15_1',  'ACHA_OUTROS_MAIS_SORTE_VOCE_SIM_GDS_15_1',],


# --- KCCQ-12 ---
'kccq_1a_banho':['TOMAR_BANHO_FUI_LIMITADO_OUTRAS_RAZOES_1',  'TOMAR_BANHO_LIMITOU_BASTANTE_1',  'TOMAR_BANHO_LIMITOU_MUITISSIMO_1',
        'TOMAR_BANHO_LIMITOU_MUITO_POUCO_1', 'TOMAR_BANHO_LIMITOU_UM_POUCO_1',  'TOMAR_BANHO_NAO_LIMITOU_2'],
'kccq_1b_caminho':['CAMINHAR_QUARTEIRAO_TERRENO_PLANO_FUI_LIMITADO_OUTRAS_RAZOES_NAO_FIZ_TAL_ATIVIDADE_1',  'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_LIMITOU_BASTANTE_1',
 		'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_LIMITOU_MUITISSIMO_1',  'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_LIMITOU_MUITO_POUCO_1',
 		'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_LIMITOU_UM_POUCO_1',  'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_NAO_LIMITOU_1',],
'kcc1_1c_correr':['CORRER_ANDAR_APRESSADAMENTE_FUI_LIMITADO_POR_OUTRAS_RAZOES_1',  'CORRER_ANDAR_APRESSADAMENTE_LIMITOU_BASTANTE_1',
 		'CORRER_ANDAR_APRESSADAMENTE_LIMITOU_MUITISSIMO_1',  'CORRER_ANDAR_APRESSADAMENTE_LIMITOU_MUITO_POUCO_1',
 		'CORRER_ANDAR_APRESSADAMENTE_LIMITOU_UM_POUCO_1',  'CORRER_ANDAR_APRESSADAMENTE_NAO_LIMITOU_1',],
'tb_kccq_2':['1_2_VEZES_POR_SEMANA_QUESTAO_2_1', '3_OU_MAIS_VEZES_POR_SEMANA_POREM_NAO_TODOS_OS_DIAS_QUESTAO_2_1', 'MENOS_DE_1_VEZ_POR_SEMANA_QUASTAO_2_1',
        'NENHUMA_VEZ_NAS_2_ULTIMAS_SEMANAS_QUESTAO_2_1', 'TODAS_AS_MANHAS_QUESTAO_2_1',],
'tb_kccq_3':[ '1_2_VEZES_POR_SEMANA_QUESTAO_3_1', '3_OU_MAIS_VEZES_POR_SEMANA_POREM_NAO_TODOS_OS_DIAS_QUESTAO_3_1', 'MENOS_DE_1_POR_SEMANA_QUESTAO_3_1',
        'NENHUMA_VEZ_NAS_2_ULTIMAS_SEMANAS_QUESTAO_3_1', 'O_TEMPO_TODO_QUESTAO_3_1', 'PELO_MENOS_1_VEZES_POR_DIA_QUESTAO_3_1', 'VARIA_VEZES_POR_DIA_QUESTAO_3_1',],
'tb_kccq_4':['1_2_VEZES_POR_SEMANA_QUESTAO_4_1', '3_OU_MAIS_VEZES_POR_SEMANA_POREM_NAO_TODOS_OS_DIAS_QUESTAO_4_1', 'MENOS_DE_1_POR_SEMANA_QUESTAO_4_1', 
        'NENHUMA_VEZ_NAS_2_ULTIMAS_SEMANAS_QUESTAO_4_1', 'O_TEMPO_TODO_QUESTAO_4_1', 'PELO_MENOS_1_VEZES_POR_DIA_QUESTAO_4_1', 'VARIA_VEZES_POR_DIA_QUESTAO_4_1',],
'tb_kccq_5':[ '1_2_VEZES_POR_SEMANA_QUESTAO_5_1',  '3_OU_MAIS_VEZES_POR_SEMANA_POREM_NAO_TODAS_AS_NOITES_QUESTAO_5_1', 'MENOS_DE_1_POR_SEMANA_QUESTAO_5_1',
        'NENHUMA_VEZ_NAS_2_ULTIMAS_SEMANAS_QUESTAO_5_1', 'O_TEMPO_TODOS_QUESTAO_5_1',],
'tb_kccq_6':['IMPEDIU_BASTANTE_QUESTAO_6_1',  'IMPEDIU_MUITISSIMO_QUESTAO_6_1',  'IMPEDIU_MUITO_POUCO_QUESTAO_6_1',  'IMPEDIU_UM_POUCO_QUESTAO_6_1', 
        'NAO_IMPEDIU_EM_NADA_QUESTAO_6_1',],
'tb_kccq_7':['BASTANTE_INSATISFEITO_QUESTAO_7_1',  'BASTANTE_SATISFEITO_QUESTAO_7_1', 'TOTALMENTE_INSATISFEITO_QUESTAO_7_1',  'TOTALMENTE_SATISFEITO_QUESTAO_7_1',
        'UM_POUCO_SATISFEITO_QUESTAO_7_1',],
'kccq_8a_passatempos':['PASSATEMPOS_ATIVIDADES_RECREATIVAS_FUI_LIMITADO_POR_OUTROS_RAZOES_1',  'PASSATEMPOS_ATIVIDADES_RECREATIVAS_LIMITOU_BASTANTE_1',
        'PASSATEMPOS_ATIVIDADES_RECREATIVAS_LIMITOU_MUITISSIMO_1',  'PASSATEMPOS_ATIVIDADES_RECREATIVAS_LIMITOU_MUITO_POUCO_1',
        'PASSATEMPOS_ATIVIDADES_RECREATIVAS_LIMITOU_UM_POUCO_1',  'PASSATEMPOS_ATIVIDADES_RECREATIVAS_NAO_LIMITOU_1',],
'kccq_8b_tarefas':['TRABALHAR_FAZER_TAREFAS_DOMESTICAS_FUI_LIMITADO_POR_OUTRAS_RAZOES_1',  'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_LIMITOU_BASTANTE_1',
        'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_LIMITOU_MUITISSIMO_1',  'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_LIMITOU_MUITO_POUCO_1',
        'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_LIMITOU_UM_POUCO_1',  'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_NAO_LIMITOU_1',],
'kccq_8c_visitas':['VISITAR_PARENTES_OU_AMIGOS_FUI_LIMITADO_POR_OUTRAS_RAZOES_1',  'VISITAR_PARENTES_OU_AMIGOS_LIMITOU_BASTANTE_1',
        'VISITAR_PARENTES_OU_AMIGOS_LIMITOU_MUITISSIMO_1',  'VISITAR_PARENTES_OU_AMIGOS_LIMITOU_MUITO_POUCO_1',  'VISITAR_PARENTES_OU_AMIGOS_LIMITOU_UM_POUCO_1',
        'VISITAR_PARENTES_OU_AMIGOS_NAO_LIMITOU_1'],


# --- EQ5D ---
'eq5d_mobilidade':['NAO_TENHO_PROBLEMAS_ANDAR_MOBILIDADE_EQ_5D_1', 'TENHO_ALGUNS_PROBLEMAS_ANDAR_MOBILIDADE_EQ_5D_1', 'TENHO_DE_ESTAR_NA_CAMA_MOBILIDADE_EQ_5D_1',],
'eq5d_cuidados_pessoais':['NAO_TENHO_PROBLEMAS_EM_CUIDAR_DE_MIM_CUIDADOS_PESSOAIS_EQ_5D_1', 'TENHO_ALGUNS_PROBLEMAS_A_LAVAR_ME_OU_VESTIR_ME_CUIDADOS_PESSOAIS_EQ_5D_1',
        'SOU_INCAPAZ_DE_ME_LAVAR_OU_VESTIR_SOZINHO_CUIDADOS_PESSOAIS_EQ_5D_1',],
'eq5d_atividades_habituais':['NAO_TENHO_PROBLEMAS_EM_DESEMPENHAR_AS_MINHAS_ATIVIDADES_HABITUAIS_ATIVIDADES_HABITUAIS_5Q_5D_1', 
        'TENHO_ALGUNS_PROBLEMAS_EM_DESEMPENHAR_AS_MINHAS_ATIVIDADES_HABITUAIS_ATIVIDADES_HABITUAIS_5Q_5D_1',
  		'SOU_INCAPAZ_DE_DESEMPENHAR_AS_MINHAS_ATIVIDADES_HABITUAIS_ATIVIDADES_HABITUAIS_5Q_5D_1',],
'eq5d_dor': ['NAO_TENHO_DORES_OU_MAL_ESTAR_DOR_MAL_ESTAR_EQ_5D_1', 'TENHO_DORES_OU_MAL_ESTAR_EXTREMOS_DOR_MAL_ESTAR__1',
 		'TENHO_DORES_OU_MAL_ESTAR_MODERADOS_DOR_MAL_ESTAR_5Q_5D_1',],
'eq5d_ansiedade':['NAO_ESTOU_ANSIOSO_OU_DEPRIMIDO_ANSIEDADE_DEPRESSAO_EQ_5D_1', 'ESTOU_EXTREMAMENTE_ANSIOSO_OU_DEPRIMIDO_ANSIEDADE_DEPRESSAO_EQ_5D_1',
 		'ESTOU_MODERAMENTE_ANSIOSO_OU_DEPRIMIDO_ANSIEDADE_DEPRESSAO_EQ_5D_1',],
'eq5d_comparacao_12meses':['MELHOR_COMPARACAO_COM_O_ULTIMO_ANO_1', 'O_MESMO_COMPARACAO_COM_O_ULTIMO_ANO_1', 'PIOR_COMPARACAO_COM_O_ULTIMO_ANO_1',],


}

#Atribuindo valores mapeados, binarios
geronto_rn = {
    # --- LINDA FRIED (0=Não, 1=Sim) ---
    'PERDA_PESO_NAO_INTENCIONAL_NAO_1': 0,
    'PERDA_PESO_NAO_INTENCIONAL_SIM_1': 1,
    'FADIGA_EXAUSTAO_AUTORREFERIDA_NAO_1': 0,
    'FADIGA_EXAUSTAO_AUTORREFERIDA_SIM_1': 1,
    'FORCA_MUSCULAR_REDUZIDA_NAO_1': 0,
    'FORCA_MUSCULAR_REDUZIDA_SIM_1': 1,
    'VELOCIDADE_MARCHA_LENTA_NAO_1': 0,
    'VELOCIDADE_MARCHA_LENTA_SIM_1': 1,
    'BAIXO_NIVEL_ATIVIDADE_FISICA_NAO_1': 0,
    'BAIXO_NIVEL_ATIVIDADE_FISICA_SIM_1': 1,

    # --- BARTHEL (Scores variados) ---
    # Alimentação
    'INDEPENDENTE_ALIMENTACAO_1': 10,
    'PRECISA_AJUDA_ALIMENTACAO_1': 5,
    'INCAPACITADO_ALIMENTACAO_1': 0,
    # Banho
    'INDEPENDENTE_BANHO_1': 5,
    'DEPENDENTE_BANHO_1': 0,
    # Higiene
    'INDEPENDENTE_ATIVIDADES_ROTINEIRAS_1': 5,
    'PRECISA_AJUDA_HIGIENE_PESSOAL_ATIVIDADE_ROTINEIRAS_1': 0,
    # Vestir
    'INDEPENDENTE_VESTIR_SE_1': 10,
    'PRECISA_AJUDA_VESTIR_SE_1': 5,
    'DEPENDENTE_VESTIR_SE_1': 0,
    # Intestino
    'CONTINENTE_INTESTINO_1': 10,
    'ACIDENTE_OCASIONAL_INTESTINO_1': 5,
    'INCONTINENTE_INTESTINO_1': 0,
    # Bexiga
    'CONTINENTE_SISTEMA_URINARIO_1': 10,
    'ACIDENTE_OCASIONAL_SISTEMA_URINARIO_1': 5,
    'INCONTINENTE_CATETERIZADIZADO_INCAPAZ_MANEJO_SISTEMA_URINARIO_1': 0,
    # Vaso
    'INDEPENDENTE_USO_BANHEIRO_1': 10,
    'PRECISA_ALGUMA_AJUDA_PARCIAL_USO_BANHEIRO_1': 5,
    'DEPENDENTE_USO_BANHEIRO_1': 0,
    # Transferência
    'INDEPENDENTE_TRANSFERENCIA_1': 15,
    'POUCA_AJUDA_TRANSFERENCIA_1': 10,
    'MUITA_AJUDA_TRANSFERENCIA_1': 5,
    'INCAPACITADO_TRANSFERENCIA_1': 0,
    # Mobilidade
    'INDEPENDENTE_MOBILIDADE_1': 15,
    'CAMINHA_AJUDA_PESSOA_MOBILIDADE_1': 10,
    'CADEIRAS_RODAS_INDEPENDENTE_MOBILIDADE_1': 5,
    'IMOVEL_MOBILIDADE_1': 0,
    # Escadas
    'INDEPENDENTE_ESCADAS_1': 10,
    'PRECISA_AJUDA_ESCADAS_1': 5,
    'INCAPACITADO_ESCADAS_1': 0,

    # --- LAWTON ---
    'USAR_TELEFONE_NAO_AIVD_1': 0,
    'USAR_TELEFONE_SIM_AIVD_1': 1,
    'FAZER_COMPRAS_NAO_AIVD_1': 0,  
    'FAZER_COMPRAS_SIM_AIVD_1': 1,
	'PREPARAR_REFEICOES_NAO_AIVD_1': 0,  
	'PREPARAR_REFEICOES_SIM_AIVD_1': 1,
	'CUIDAR_CASA_NAO_AIVD_1': 0,  
	'CUIDAR_CASA_SIM_AIVD_1': 1,
	'LAVAR_ROUPA_NAO_AIVD_1': 0,  
	'LAVAR_ROUPA_SIM_AIVD_1': 1,
	'USAR_MEIOS_TRANSPORTE_NAO_AIVD_1': 0,  
	'USAR_MEIOS_TRANSPORTE_SIM_AIVD_1': 1,
	'RESPONSABILIDADE_MEDICAMENTOS_NAO_AIVD_1': 0,  
	'RESPONSABILIDADE_MEDICAMENTOS_SIM_AIVD_1': 1,
	'GERENCIAR_FINANCAS_NAO_AIVD_1': 0,  
	'GERENCIAR_FINANCAS_SIM_AIVD_1': 1,
    

    # --- SARC-F (0=Nenhuma, 1=Alguma, 2=Muita) ---
    # Força
    'DIFICULDADE_LEVANTAR_CARREGAR_NENHUMA_SARC_F_1': 0,
    'DIFICULDADE_LEVANTAR_CARREGAR_ALGUMA_SARC_F_1': 1,
    'DIFICULDADE_LEVANTAR_CARREGAR_MUITA_SARC_F_1': 2,
    # Caminhada
    'CAMINHAR_DENTRO_COMODO_NENHUMA_SARC_F_1': 0,
    'CAMINHAR_DENTRO_COMODO_ALGUMA_SARC_F_1': 1,
    'CAMINHAR_DENTRO_COMODO_MUITA_SARC_F_1': 2,
    # Levantar Cadeira
    'LEVANTAR_DE_UMA_CADEIRA_NENHUMA_SARC_F_1': 0,
    'LEVANTAR_DE_UMA_CADEIRA_ALGUMA_SARC_F_1': 1,
    'LEVANTAR_DE_UMA_CADEIRA_MUITA_SARC_F_1': 2,
    # Escadas
    'SUBIR_LANCE_10_DEGRAUS_NENHUMA_SARC_F_1': 0,
    'SUBIR_LANCE_10_DEGRAUS_ALGUMA_SARC_F_1': 1,
    'SUBIR_LANCE_10_DEGRAUS_MUITA_SARC_F_1': 2,
    # Quedas
    'QUANTAS_VEZES_CAIU_ULTIMO_ANO_NENHUMA_SARC_F_1': 0,
    'QUANTAS_VEZES_CAIU_ULTIMO_ANO_ALGUMA_SARC_F_1': 1,
    'QUANTAS_VEZES_CAIU_ULTIMO_ANO_MUITA_SARC_F_1': 2,

    # --- APGAR FAMILIAR (0=Raramente, 1=Algumas vezes, 2=Quase sempre) ---
    'SATIFEITO_AJUDA_RECEBE_SUA_FAMILIA_QUANDO_ALGUM_PROBLEMA_RARAMENTE_APGAR_FAMILIAR_1': 0,
    'SATIFEITO_AJUDA_RECEBE_SUA_FAMILIA_QUANDO_ALGUM_PROBLEMA_ALGUMAS_VEZES_APGAR_FAMILIAR_1': 1,
    'SATIFEITO_AJUDA_RECEBE_SUA_FAMILIA_QUANDO_ALGUM_PROBLEMA_QUASE_SEMPRE_APGAR_FAMILIAR_1': 2,
    'SATIFEITO_FORMA_COMO_SUA_FAMILIA_CONVERSA_SOBRE_PROBLEMAS_ALGUMAS_VEZES_APGAR_FAMILIAR_1': 1,
 	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_CONVERSA_SOBRE_PROBLEMAS_QUASE_SEMPRE_APGAR_FAMILIAR_1': 2,
 	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_CONVERSA_SOBRE_PROBLEMAS_RARAMENTE_APGAR_FAMILIAR_1': 0,
	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_ACEITA_SUES_DESEJOS_ALGUMAS_VEZES_APGAR_FAMILIAR_1': 1,
 	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_ACEITA_SUES_DESEJOS_QUASE_SEMPRE_APGAR_FAMILIAR_1': 2,
 	'SATIFEITO_FORMA_COMO_SUA_FAMILIA_ACEITA_SUES_DESEJOS_RARAMENTE_APGAR_FAMILIAR_1': 0,
	'SATIFEITO_FORMA_COMO_PODE_CONTAR_FAMILIA_SITUACOES_DIFICEIS_ALGUMAS_VEZES_APGAR_FAMILIAR_1': 1,
 	'SATIFEITO_FORMA_COMO_PODE_CONTAR_FAMILIA_SITUACOES_DIFICEIS_QUASE_SEMPRE_APGAR_FAMILIAR_1': 2,
 	'SATIFEITO_FORMA_COMO_PODE_CONTAR_FAMILIA_SITUACOES_DIFICEIS_RARAMENTE_APGAR_FAMILIAR_1': 0,
	'SATIFEITO_COM_TEMPO_FAMILIA_JUNTOS_ALGUMAS_VEZES_APGAR_FAMILIAR_1': 1,
 	'SATIFEITO_COM_TEMPO_FAMILIA_JUNTOS_QUASE_SEMPRE_APGAR_FAMILIAR_1': 2,
 	'SATIFEITO_COM_TEMPO_FAMILIA_JUNTOS_RARAMENTE_APGAR_FAMILIAR_1': 0,
	
	# --- GDS-15 ---
	'ESTA_SATISFEIRO_COM_SUA_VIDA_NAO_GDS_15_1': 0,  
    'ESTA_SATISFEIRO_COM_SUA_VIDA_SIM_GDS_15_1': 1,
	'INTERROMPEU_MUITA_ATIVIDADES_NAO_GDS_15_1': 0,  
	'INTERROMPEU_MUITA_ATIVIDADES_SIM_GDS_15_1': 1,
	'ACHA_SUA_VIDA_VAZIA_NAO_GDS_15_1': 0,  
	'ACHA_SUA_VIDA_VAZIA_SIM_GDS_15_1': 1,
	'ABORRECE_SE_COM_FREQUENCIA_NAO_GDS_15_1': 0,  
	'ABORRECE_SE_COM_FREQUENCIA_SIM_GDS_15_1': 1,
	'SENTE_SE_BEM_COM_VIDA_MAIOR_PARTE_TEMPO_NAO_GDS_15_1': 0,  
	'SENTE_SE_BEM_COM_VIDA_MAIOR_PARTE_TEMPO_SIM_GDS_15_1': 1,
	'TEME_QUE_ALGO_RUIM_LHE_ACONTECA_NAO_GDS_15_1': 0,  
	'TEME_QUE_ALGO_RUIM_LHE_ACONTECA_SIM_GDS_15_1': 1,
	'SENTE_SE_ALEGRE_MAIOR_PARTE_TEMPO_NAO_GDS_15_1': 0,  
	'SENTE_SE_ALEGRE_MAIOR_PARTE_TEMPO_SIM_GDS_15_1': 1,
	'SENTE_SE_DESAMPARADO_COM_FREQUENCIA_NAO_GDS_15_1': 0,  
	'SENTE_SE_DESAMPARADO_COM_FREQUENCIA_SIM_GDS_15_1': 1,
	'PREFERE_FICAR_CASA_SAIR_FAZER_COISAS_NOVAS_NAO_GDS_15_1': 0,  
	'PREFERE_FICAR_CASA_SAIR_FAZER_COISAS_NOVAS_SIM_GDS_15_1': 1,
	'ACHA_MAIS_PROBLEMAS_MEMORIA_OUTRAS_PESSOAS_NAO_GDS_15_1': 0,  
	'ACHA_MAIS_PROBLEMAS_MEMORIA_OUTRAS_PESSOAS_SIM_GDS_15_1': 1,
	'ACHA_MARAVILHOSO_VIVO_NAO_GDS_15_1': 0,  
	'ACHA_MARAVILHOSO_VIVO_SIM_GDS_15_1': 1,
	'SENTE_SE_INUTIL_NAO_GDS_15_1': 0,  
	'SENTE_SE_INUTIL_SIM_GDS_15_1': 1,
	'SENTE_SE_CHEIO_DE_ENERGIA_NAO_GDS_15_1': 0,  
	'SENTE_SE_CHEIO_DE_ENERGIA_SIM_GDS_15_1': 1,
	'SENTE_SE_SEM_ESPERANCA_NAO_GDS_15_1': 0,  
	'SENTE_SE_SEM_ESPERANCA_SIM_GDS_15_1': 1,
	'ACHA_OUTROS_MAIS_SORTE_VOCE_NAO_GDS_15_1': 0,  
	'ACHA_OUTROS_MAIS_SORTE_VOCE_SIM_GDS_15_1': 1,
	

    # --- KCCQ-12 ---
    'TOMAR_BANHO_LIMITOU_MUITISSIMO_1': 1,
    'TOMAR_BANHO_LIMITOU_BASTANTE_1': 2,
    'TOMAR_BANHO_LIMITOU_UM_POUCO_1': 3,
    'TOMAR_BANHO_LIMITOU_MUITO_POUCO_1': 4,
    #'TOMAR_BANHO_NAO_LIMITOU_1': 5,
    'TOMAR_BANHO_NAO_LIMITOU_2': 5,
    'TOMAR_BANHO_FUI_LIMITADO_OUTRAS_RAZOES_1': 0, 
	'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_FUI_LIMITADO_OUTRAS_RAZOES_NAO_FIZ_TAL_ATIVIDADE_1': 0,  
	'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_LIMITOU_BASTANTE_1': 2,
 	'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_LIMITOU_MUITISSIMO_1': 1,  
	'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_LIMITOU_MUITO_POUCO_1': 4,
 	'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_LIMITOU_UM_POUCO_1': 3,  
	'CAMINHAR_QUARTEIRAO_TERRENO_PLANO_NAO_LIMITOU_1': 5,
	'CORRER_ANDAR_APRESSADAMENTE_FUI_LIMITADO_POR_OUTRAS_RAZOES_1': 0,  
	'CORRER_ANDAR_APRESSADAMENTE_LIMITOU_BASTANTE_1': 2,
 	'CORRER_ANDAR_APRESSADAMENTE_LIMITOU_MUITISSIMO_1': 1,  
	'CORRER_ANDAR_APRESSADAMENTE_LIMITOU_MUITO_POUCO_1': 4,
 	'CORRER_ANDAR_APRESSADAMENTE_LIMITOU_UM_POUCO_1': 3,  
	'CORRER_ANDAR_APRESSADAMENTE_NAO_LIMITOU_1': 5,
	'1_2_VEZES_POR_SEMANA_QUESTAO_2_1': 3, 
	'3_OU_MAIS_VEZES_POR_SEMANA_POREM_NAO_TODOS_OS_DIAS_QUESTAO_2_1': 2, 
	'MENOS_DE_1_VEZ_POR_SEMANA_QUASTAO_2_1': 4,
    'NENHUMA_VEZ_NAS_2_ULTIMAS_SEMANAS_QUESTAO_2_1': 5, 
	'TODAS_AS_MANHAS_QUESTAO_2_1': 1,
	'1_2_VEZES_POR_SEMANA_QUESTAO_3_1': 5, 
	'3_OU_MAIS_VEZES_POR_SEMANA_POREM_NAO_TODOS_OS_DIAS_QUESTAO_3_1': 4, 
	'MENOS_DE_1_POR_SEMANA_QUESTAO_3_1': 6,
    'NENHUMA_VEZ_NAS_2_ULTIMAS_SEMANAS_QUESTAO_3_1': 7, 
	'O_TEMPO_TODO_QUESTAO_3_1': 1, 
	'PELO_MENOS_1_VEZES_POR_DIA_QUESTAO_3_1': 3, 
	'VARIA_VEZES_POR_DIA_QUESTAO_3_1': 2,
	'1_2_VEZES_POR_SEMANA_QUESTAO_4_1': 5, 
	'3_OU_MAIS_VEZES_POR_SEMANA_POREM_NAO_TODOS_OS_DIAS_QUESTAO_4_1': 4, 
	'MENOS_DE_1_POR_SEMANA_QUESTAO_4_1': 6, 
    'NENHUMA_VEZ_NAS_2_ULTIMAS_SEMANAS_QUESTAO_4_1': 7, 
	'O_TEMPO_TODO_QUESTAO_4_1': 1, 
	'PELO_MENOS_1_VEZES_POR_DIA_QUESTAO_4_1': 3, 
	'VARIA_VEZES_POR_DIA_QUESTAO_4_1': 2,
	'1_2_VEZES_POR_SEMANA_QUESTAO_5_1': 3,  
	'3_OU_MAIS_VEZES_POR_SEMANA_POREM_NAO_TODAS_AS_NOITES_QUESTAO_5_1': 2, 
	'MENOS_DE_1_POR_SEMANA_QUESTAO_5_1': 4,
    'NENHUMA_VEZ_NAS_2_ULTIMAS_SEMANAS_QUESTAO_5_1': 5, 
	'O_TEMPO_TODOS_QUESTAO_5_1': 1,
	'IMPEDIU_BASTANTE_QUESTAO_6_1': 2,  
	'IMPEDIU_MUITISSIMO_QUESTAO_6_1': 1,  
	'IMPEDIU_MUITO_POUCO_QUESTAO_6_1': 4,  
	'IMPEDIU_UM_POUCO_QUESTAO_6_1': 3, 
    'NAO_IMPEDIU_EM_NADA_QUESTAO_6_1': 5,
	'BASTANTE_INSATISFEITO_QUESTAO_7_1': 2,  
	'BASTANTE_SATISFEITO_QUESTAO_7_1': 4, 
	'TOTALMENTE_INSATISFEITO_QUESTAO_7_1': 1,  
	'TOTALMENTE_SATISFEITO_QUESTAO_7_1': 5,
    'UM_POUCO_SATISFEITO_QUESTAO_7_1': 3,
	'PASSATEMPOS_ATIVIDADES_RECREATIVAS_FUI_LIMITADO_POR_OUTROS_RAZOES_1': 0,  
	'PASSATEMPOS_ATIVIDADES_RECREATIVAS_LIMITOU_BASTANTE_1': 2,
    'PASSATEMPOS_ATIVIDADES_RECREATIVAS_LIMITOU_MUITISSIMO_1': 1,  
	'PASSATEMPOS_ATIVIDADES_RECREATIVAS_LIMITOU_MUITO_POUCO_1': 4,
    'PASSATEMPOS_ATIVIDADES_RECREATIVAS_LIMITOU_UM_POUCO_1': 3,  
	'PASSATEMPOS_ATIVIDADES_RECREATIVAS_NAO_LIMITOU_1': 5,
	'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_FUI_LIMITADO_POR_OUTRAS_RAZOES_1': 0,  
	'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_LIMITOU_BASTANTE_1': 2,
    'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_LIMITOU_MUITISSIMO_1': 1,  
	'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_LIMITOU_MUITO_POUCO_1': 4,
    'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_LIMITOU_UM_POUCO_1': 3,  
	'TRABALHAR_FAZER_TAREFAS_DOMESTICAS_NAO_LIMITOU_1': 5,
	'VISITAR_PARENTES_OU_AMIGOS_FUI_LIMITADO_POR_OUTRAS_RAZOES_1': 0,  
	'VISITAR_PARENTES_OU_AMIGOS_LIMITOU_BASTANTE_1': 2,
    'VISITAR_PARENTES_OU_AMIGOS_LIMITOU_MUITISSIMO_1': 1,  
	'VISITAR_PARENTES_OU_AMIGOS_LIMITOU_MUITO_POUCO_1': 4,  
	'VISITAR_PARENTES_OU_AMIGOS_LIMITOU_UM_POUCO_1': 3,
    'VISITAR_PARENTES_OU_AMIGOS_NAO_LIMITOU_1': 5,
	

	# --- EQ5D ---
	'NAO_TENHO_PROBLEMAS_ANDAR_MOBILIDADE_EQ_5D_1': 1, 
	'TENHO_ALGUNS_PROBLEMAS_ANDAR_MOBILIDADE_EQ_5D_1': 2,
	'TENHO_DE_ESTAR_NA_CAMA_MOBILIDADE_EQ_5D_1': 3,
	'NAO_TENHO_PROBLEMAS_EM_CUIDAR_DE_MIM_CUIDADOS_PESSOAIS_EQ_5D_1': 1, 
	'TENHO_ALGUNS_PROBLEMAS_A_LAVAR_ME_OU_VESTIR_ME_CUIDADOS_PESSOAIS_EQ_5D_1': 2,
	'SOU_INCAPAZ_DE_ME_LAVAR_OU_VESTIR_SOZINHO_CUIDADOS_PESSOAIS_EQ_5D_1': 3,
	'NAO_TENHO_PROBLEMAS_EM_DESEMPENHAR_AS_MINHAS_ATIVIDADES_HABITUAIS_ATIVIDADES_HABITUAIS_5Q_5D_1': 1, 
	'TENHO_ALGUNS_PROBLEMAS_EM_DESEMPENHAR_AS_MINHAS_ATIVIDADES_HABITUAIS_ATIVIDADES_HABITUAIS_5Q_5D_1': 2,
	'SOU_INCAPAZ_DE_DESEMPENHAR_AS_MINHAS_ATIVIDADES_HABITUAIS_ATIVIDADES_HABITUAIS_5Q_5D_1': 3,
	'NAO_TENHO_DORES_OU_MAL_ESTAR_DOR_MAL_ESTAR_EQ_5D_1': 1, 
	'TENHO_DORES_OU_MAL_ESTAR_EXTREMOS_DOR_MAL_ESTAR__1': 3,
	'TENHO_DORES_OU_MAL_ESTAR_MODERADOS_DOR_MAL_ESTAR_5Q_5D_1': 2,
	'NAO_ESTOU_ANSIOSO_OU_DEPRIMIDO_ANSIEDADE_DEPRESSAO_EQ_5D_1': 1, 
	'ESTOU_EXTREMAMENTE_ANSIOSO_OU_DEPRIMIDO_ANSIEDADE_DEPRESSAO_EQ_5D_1': 3,
	'ESTOU_MODERAMENTE_ANSIOSO_OU_DEPRIMIDO_ANSIEDADE_DEPRESSAO_EQ_5D_1': 2,
	'MELHOR_COMPARACAO_COM_O_ULTIMO_ANO_1': 1, 
	'O_MESMO_COMPARACAO_COM_O_ULTIMO_ANO_1': 2, 
	'PIOR_COMPARACAO_COM_O_ULTIMO_ANO_1': 3,


}

#Mapeamento direto, trocando nomes de colunas
geronto_maps = {
    'CD_PACIENTE': 'record_id', 
    'CD_ATENDIMENTO': 'cd_atendimento',

	# --- LF ---
	'CRITERIOS_FRAGILIDADE_LINDA_FRIED_1': 'lf_criterios_presentes',

	# --- SPPB ---
	'EQUILIBRIO_SPPB_1': 'sppb_equilibrio',
	'MARCHA_TEMPO_SPPB_1': 'sppb_marcha_tempo',
	'MARCHA_SPPB_1': 'sppb_marcha_pontos',
	'LEVANTAR_SENTAR_CADEIRA_TEMPO_SPPB_1': 'sppb_cadeira_tempo',
	'LEVANTAR_SENTAR_CADEIRA_SPPB_1': 'sppb_cadeira_pontos',
	'SPPB_SHORT_PHYSICAL_PERFORMANCE_BATTERY_1': 'sppb_escore_total',

	# --- BARTHEL ---
	'ATIVIDADE_BASICAS_VIDA_DIARIA_AVD_BARTHEL_1': 'barthel_score_total',
	
	# --- LAWTON ---
	'ATIVIDADES_INSTRUMENTAIS_VIDA_DIARIA_AIVD_LAWTON_1': 'lawton_score_total',

	# --- SARCF ---
	'SARC_F_RISCO__1': 'sarcf_score_total',

	# --- APGAR FAMILIAR ---
	'APGAR_FAMILIAR_1': 'apgar_score_total',

	# --- GDS-15 ---
	'ESCALA_DEPRESSAO_GERIATRICA_GDS_15_1': 'gds15_score_total',

	# --- KCCQ-12 ---
	'RESULTADO_KCCQ_12_1': 'kccq_score_resumo_geral',
    
	# --- EQ5D ---
	'DE_0_ATE_100_QUANTO_VOCE_AVALIA_SAUDE_HOJE_EQ5D_1': 'eq5d_escala_estado_saude',
    
	# --- MEEM ---
	'MINI_EXAME_ESTADO_MENTAL_MEEM_1': 'meem_score_total',
	'QUAL_DIA_SEMANA_ORIENTACAO_ESPACIAL_MEEM_1': 'meem_weekday',
	'QUAL_MES_ORIENTACAO_ESPACIAL_MEEM_1': 'meem_month',
	'QUAL_DIA_MES_ORIENTACAO_ESPACIAL_MEEM_1': 'meem_monthday',
	'QUAL_ANO_ORIENTACAO_ESPACIAL_MEEM_1': 'meem_year',
	'QUAL_HORA_APROXIMADA_ORIENTACAO_ESPACIAL_MEEM_1': 'meem_hour',
	'ONDE_ESTAMOS_LOCAL_ORIENTACAO_TEMPORAL_ESPACIAL_MEEM_1': 'meem_local',
	'ONDE_ESTAMOS_INSTITUICAO_ORIENTACAO_TEMPORAL_ESPACIAL_MEEM_1': 'meem_instituicao',
	'ONDE_ESTAMOS_BAIRRO_ORIENTACAO_TEMPORAL_ESPACIAL_MEEM_1': 'meem_bairro',
	'ONDE_ESTAMOS_CIDADE_ORIENTACAO_TEMPORAL_ESPACIAL_MEEM_1': 'meem_cidade',
	'ONDE_ESTAMOS_ESTADO_ORIENTACAO_TEMPORAL_ESPACIAL_MEEM_1': 'meem_estado',
	'MENCIONE_3_PALAVRAS_MEEM_1': 'meem_reg_word_1',
	'MENCIONE_3_PALAVRAS_MEEM_2': 'meem_reg_word_2',
	'MENCIONE_3_PALAVRAS_MEEM_3': 'meem_reg_word_3',
	'SETE_SERIADO_ATENCAO_CALCULO_MEEM_1': 'meem_calculo',
	'PERGUNTE_NOME_3_PALAVRAS_APRENDIDOS_MEEM_1': 'meem_evoc_word_1',
	'PERGUNTE_NOME_3_PALAVRAS_APRENDIDOS_MEEM_2': 'meem_evoc_word_2',
	'PERGUNTE_NOME_3_PALAVRAS_APRENDIDOS_MEEM_3': 'meem_evoc_word_3',
	'APONTE_LAPIS_RELOGIO_FACA_PACIENTE_DIZER_NOME_OBJETOS_CONFORME_APONTA_LIGUAGEM_MEEM_1': 'meem_objeto',
	'FACA_PACIENTE_REPETIR_LIGUAGEM_MEEM_1': 'meem_repeat_frase',
	'FACA_PACIENTE_SEGUIR_COMANDO_LINGUAGEM_MEEM_1': 'meem_comando_verbal',
	'FACA_PACIENTE_LER_OBEDECER_LINGUAGEM_MEEM_1': 'meem_ler_obedecer',
	'FACA_PACIENTE_ESCREVER_FRASE_PROPRIA_AUTORIA_LINGUAGEM_MEEM_1': 'meem_escrever_frase',
	'RESULTADO_COPIE_DESENHO_ABAIXO_MEEM_1': 'meem_copiar_desenho',
    
	# --- OUTRAS COLUNAS ---
	'ALTURA_MAPAR_1': 'altura',
    'BRANQUIAL_CM_1': 'circ_braquial_cm',
    'CINTURA_CM_1': 'circ_abdomen_cm',
    'PANTURRILHA_CM_1': 'circ_panturilha_cm',
    'PESO_MAPA_1': 'peso',
    'TC6M_TESTE_CAMINHADA_SEIS_MUNITOS_1': 'caminhada_metro',
    'METROS_POR_SEGUNDOS_1': 'caminhada_6min',
    'OBSERVACAO_AVALIACAO_GERONTOLOGICA_1':'final_observacao'

}

#Colunas para excluir
geronto_cols_excluir = {'DATAID',
 'CD_DOCUMENTO',
 'DS_DOCUMENTO',
 'DS_LEITO',
 'CD_PRESTADOR',
 'NM_PRESTADOR',
 'NM_SETOR', 'apgar_score_total', 'lawton_score_total',
 'barthel_score_total', 'lf_criterios_presentes',
 'gds15_score_total', 'FORCA_MUSCULAR_REDUZIDA_OBSERVACAO_1',
 'FORCA_MUSCULAR_REDUZIDA_OBSERVACAO_2',
 'IMC_AVALIACAO_GERONTOLOGICA_1',
 'INTERPRETACAO_AVD_BARTHEL_1',
 'sppb_cadeira_pontos', 'sppb_marcha_pontos', 'meem_score_total', 'QUADRILATERO_1', 'kccq_score_resumo_geral',
 'sarcf_score_total','sppb_escore_total', 'VELOCIDADE_MARCHA_LENTA_OBSERVACAO_1',
 'VELOCIDADE_MARCHA_LENTA_OBSERVACAO_2', 'data_cirurgia', 'LIMITACAO_FISICA_1', 'TOTAL_FREQUENCIA_1',
 'TOTAL_LIMITACAO_SOCIAL_2',
 'TOTAL_QUALIADADE_2', 'imc'
}


# --------------------------------------
# Dicionário Mapeado Ficha 1175 - Perfusão
# --------------------------------------

#Mapeamento direto, trocando nomes de colunas
perfusao_maps = {
    'TEMPO_ANOXIA': 'tempo_pinc_ao', 
    'TEMPO_PERFUSAO': 'tempo_cec'
}

perfusao_cols_excluir = [
    'DH_DOCUMENTO', 'TXT_TIPO_CARDIOPLAGIA', 'CTX_OBSERVACAO', 
    'HEPARINA', 'PERFUSATO', 'PROTAMINA', 
    'TCA_FINAL', 'TCA_INICIAL', 'TIPO_CARDIOPLEGIA', 'adado_P_208306'
]


# --------------------------------------
# Dicionário Mapeado Descrição Cirúrgica
# --------------------------------------

#Dicionário de cirurgiões
referencia_cirurgioes = {
    'ALMIRO CARLOS FERRO JUNIOR': [200, 3],
    'ALOYSIO ABDO SILVA CAMPOS': [150, 2],
    'ANDRE LUIZ MENDES MARTINS': [200, 2],
    'ANDREA CRISTINA OLIVEIRA FREITAS': [200, 3],
    'ANTONIO FLAVIO SANCHEZ DE ALMEIDA': [200, 3],
    'DANIEL CHAGAS DANTAS': [200, 3],
    'DIEGO GAMARRA MOREIRA': [50, 2],
    'GIOVANNA PAULA MACEDO DE LACERDA GUEDES': [100, 1],
    'JANAYNA THAINA RABELATO': [200, 3],
    'MARCELA DALLA BERNARDINA SENA': [30, 1],
    'MARIO ISSA': [200, 3],
    'OMAR ALONZO POZO IBANEZ': [200, 3],
    'PAULO HENRIQUE D PAULISTA': [200, 3],
    'RENATO TAMBELLINI ARNONI': [200, 3],
    'VITOR LUCENA CARNEIRO': [150, 2],
    'LEANDRO PICHETH ELOY PEREIRA': [30, 1]
}


# --------------------------------------
# Dicionário Mapeado Fichas  - Fisioterapia
# 62, 240, 764, 895, 898, 899, 900, 901, 902, 
# 903, 904, 905, 906, 908, 1041, 1136, 1137, 
# 1138, 1140, 1141, 1142, 1145
# --------------------------------------

#Organiza as colunas mapeadas
fisio_ls = {
 
# --- LF ---
'tosse_evol_fisio':['TOSSE_PRESENTE', 'TOSSE_AUSENTE',],
'tosse_evol_fisio_2':[ 'TOSSE_PRODUTIVA', 'TOSSE_SECA',],
'tosse_evol_fisio_3':['TOSSE_EFICAZ', 'TOSSE_INEFICAZ', 'TOSSE_POUCO_EFICAZ'],

'BIA_SN':                       		['BIA_NAO', 'BIA_SIM'],
'CUFF_RL_SN':                   		['CUFF_RL_NAO', 'CUFF_RL_SIM'],
'CUFF_TQT_SN':                  		['CUFF_TQT_NAO', 'CUFF_TQT_SIM'],
'DROGAS_VASOATIVAS_SN':      			['DROGAS_VASOATIVAS_NAO', 'DROGAS_VASOATIVAS_SIM'],
'ECMO_SN':                      		['ECMO_NAO', 'ECMO_SIM'],
'EOT_CENTRO_CIRURGICO_SN':      		['EOT_CENTRO_CIRURGICO_NAO', 'EOT_CENTRO_CIRURGICO_SIM'],
'EXTUBACAO_SN':                 		['EXTUBACAO_NAO', 'EXTUBACAO_SIM'],
'NO_SN':                        		['NO_NAO', 'NO_SIM'],
'OXIGENOTERAPIA_SN':            		['OXIGENOTERAPIA_NAO', 'OXIGENOTERAPIA_SIM'],
'POS_OPERATORIO_SN':            		['POS_OPERATORIO_NAO', 'POS_OPERATORIO_SIM'],
'VENTILACAO_MECANICA_SN':       		['VENTILACAO_MECANICA_INVASIVA_NAO', 'VENTILACAO_MECANICA_INVASIVA_SIM'],
'VENTILACAO_NAO_INVASIVA_SN':   		['VENTILACAO_NAO_INVASIVA_NAO', 'VENTILACAO_NAO_INVASIVA_SIM'],
'VIA_AEREA_ARTIFICIAL_SN':      		['VIA_AEREA_ARTIFICIAL_NAO', 'VIA_AEREA_ARTIFICIAL_SIM'],
'REINTUBACAO_SN':               		['REINTUBACAO_NAO', 'REINTUBACAO_SIM'],
'RESPIRACAO_ESPONTANEA_SN':     		['RESPIRACAO_ESPONTANEA_NAO', 'RESPIRACAO_ESPONTANEA_SIM'],
'SINAIS_DESCONFORTO_SN':        		['SINAIS_DESCONFORTO_RESPIRATORIO_NAO', 'SINAIS_DESCONFORTO_RESPIRATORIO_SIM'],
'SEDACAO_SN':							['SEDACAO_NAO_NEUROLOGICO', 'SEDACAO_SIM_NEUROLOGICO'],
'TREINAMENTO_MUSCULAR_RESPORATORIO_SN':	['TREINAMENTO_MUSCULAR_RESPORATORIO_NAO', 'TREINAMENTO_MUSCULAR_RESPORATORIO_SIM',],
'PREENSAO_PALMAR':						['NAO_TESTADO_PREENSAO_PALMAR', 'NAO_TESTADO_PRESSAO_PALMAR', 'PRESSAO_PALMAR_MEMBRO_DOMINANTE_DIREITO', 'PRESSAO_PALMAR_MEMBRO_DOMINANTE_ESQUERDO']

}

#Atribuindo valores mapeados, binarios
fisio_rn = {
    # --- ---
    'TOSSE_PRESENTE': 1,
    'TOSSE_AUSENTE': 2,
    'TOSSE_PRODUTIVA': 1,
    'TOSSE_SECA': 2,
    'TOSSE_EFICAZ': 1,
    'TOSSE_INEFICAZ': 2,
    'TOSSE_POUCO_EFICAZ': 3,
    
	'BIA_NAO': 0, 'BIA_SIM': 1,
    'CUFF_RL_NAO': 0, 'CUFF_RL_SIM': 1,
    'CUFF_TQT_NAO': 0, 'CUFF_TQT_SIM': 1,
    'DROGAS_VASOATIVAS_NAO': 0, 'DROGAS_VASOATIVAS_SIM': 1,
    'ECMO_NAO': 0, 'ECMO_SIM': 1,
    'EOT_CENTRO_CIRURGICO_NAO': 0, 'EOT_CENTRO_CIRURGICO_SIM': 1,
    'EXTUBACAO_NAO': 0, 'EXTUBACAO_SIM': 1,
    'NO_NAO': 0, 'NO_SIM': 1,
    'OXIGENOTERAPIA_NAO': 0, 'OXIGENOTERAPIA_SIM': 1,
    'POS_OPERATORIO_NAO': 0, 'POS_OPERATORIO_SIM': 1,
    'VENTILACAO_MECANICA_INVASIVA_NAO': 0, 'VENTILACAO_MECANICA_INVASIVA_SIM': 1,
    'VENTILACAO_NAO_INVASIVA_NAO': 0, 'VENTILACAO_NAO_INVASIVA_SIM': 1,
    'VIA_AEREA_ARTIFICIAL_NAO': 0, 'VIA_AEREA_ARTIFICIAL_SIM': 1,
    'REINTUBACAO_NAO': 0, 'REINTUBACAO_SIM': 1,
    'RESPIRACAO_ESPONTANEA_NAO': 0, 'RESPIRACAO_ESPONTANEA_SIM': 1,
    'SINAIS_DESCONFORTO_RESPIRATORIO_NAO': 0, 'SINAIS_DESCONFORTO_RESPIRATORIO_SIM': 1,
    'SEDACAO_NAO_NEUROLOGICO': 0, 'SEDACAO_SIM_NEUROLOGICO': 1,
    'TREINAMENTO_MUSCULAR_RESPORATORIO_NAO': 0, 'TREINAMENTO_MUSCULAR_RESPORATORIO_SIM': 1,
    
	'NAO_TESTADO_PREENSAO_PALMAR': 0, 'NAO_TESTADO_PRESSAO_PALMAR': 0, 
    'PRESSAO_PALMAR_MEMBRO_DOMINANTE_DIREITO': 1, 'PRESSAO_PALMAR_MEMBRO_DOMINANTE_ESQUERDO': 2,
    
}

#Mapeamento direto, trocando nomes de colunas
fisio_maps = {
    "SEDACAO_UTILIZADA":                     "sedacao_utilizada_evol_fisio",
    "DROGAS_VASOATIVAS":                     "quais_drogas_vasoativas_evol_fisio",
    "SINAL":                                 "sinal_evol_fisio",
    "TIPO_OXIGENOTERAPIA":                   "tipo_oxigenoterapia_evol_fisio",
    "OFERTA_TIPO":                           "oferta_oxigenoterapia_evol_fisio",
    "MODO_VENTILACAO_NAO_INVASIVA":          "modo_ventilacao_n_invasiva_evol_fisio",
    "MODO_VENTILACAO_MECANICA_INVASIVA":     "modo_vent_inv_evol_fisio",
    "DATA_EXTUBACAO":                        "fisio_dt_eot",
    "SUPORTE_APOS_EOT":                      "fisio_suporte_eot",
    'SEDACAO_SN':							 'sedacao_evol_fisio',
    'DROGAS_VASOATIVAS_SN':					 'drogas_vasoativas_evol_fisio',
    'RESPIRACAO_ESPONTANEA_SN':				 'respiracao_espontanea_evol_fisio',
 	'SINAIS_DESCONFORTO_SN':				 'sinais_desconforto_resp_evol_fisio',
    'OXIGENOTERAPIA_SN':					 'oxigenoterapia_evol_fisio',
    'VENTILACAO_NAO_INVASIVA_SN':			 'ventilacao_nao_invasiva_evol_fisio',
    'VIA_AEREA_ARTIFICIAL_SN':				 'via_aerea_artificial_evol_fisio',
 	'VENTILACAO_MECANICA_SN':				 'vent_mec_inv_evol_fisio',
    'EXTUBACAO_SN':							 'fisio_eot',
    'BIA_SN':								 'fisio_bia',
 	'NO_SN':								 'fisio_no',
 	'ECMO_SN':								 'fisio_ecmo',
    'TA_EVOLUCAO': 							 'tempo_pinc_ao',
    'TP_EVOLUCAO': 							 'tempo_cec',
    'CD_ATENDIMENTO': 						 'cd_atendimento',
    'INTERFACE':							 'interface_evol_fisio',
    'TREINAMENTO_MUSCULAR_RESPORATORIO_SN':	 'treino_musc_respiratorio',
    'REINTUBACAO_SN':						 'fisio_reiot',
    'PREENSAO_PALMAR':						 'preensao_palmar_fisio',
    'PEEP_VENTILACAO_NAO_INVASIVA':          'peep_vpm',
    'PINSP_VENTILACAO_NAO_INVASIVA':         'pinsp_vpm',
    'FR_VENTILACAO_NAO_INVASIVA':            'fr_vpm',
    'FIO2_VENTILACAO_NAO_INVASIVA':          'fio2_vpm',
    'PRESSAO_PALMAR_MEMBRO_DOMINANTE_DIREITO': 'valor_preensao_palmar',
    'DISTANCIA_PERCORRIDA_TESTE_CAMINHADA':  'distancia_percorrida_tc6m'
    
}

#Colunas para excluir
fisio_cols_excluir = {
    'NM_PRESTADOR', 'DS_LEITO', 'CD_PRESTADOR', 'CUFF_RL_SN', 'ANO',
    'CUFF_TQT_SN', 'EOT_CENTRO_CIRURGICO_SN', 'POS_OPERATORIO_SN', 'ADEQUADO_DESENVOLVIMENTO', 'ADMISSAO',
    'ALIMENTACAO_FSS', 'ALTURA_TESTE_CAMINHADA', 'AMPLITUDE_MOVIMENTO', 'ANTECEDENTES_PESSOAIS_EVOLUCAO',
    'ANTECEDENTES_PESSOAIS_SETOR_ORIGEM', 'ASSISTENCIA', 'ATENDIMENTO', 'AUSCULTA_PULMONAR_EVOLUCAO', 
    'BORG_DISPNEIA_DURANTE', 'BORG_DISPNEIA_DURANTE_CONDUTA_MOTORA', 'BORG_DISPNEIA_FINAL', 'BORG_DISPNEIA_FINAL_CONDUTA_MOTORA',
    'BORG_DISPNEIA_INICIO', 'BORG_DISPNEIA_INICIO_CONDUTA_MOTORA', 'BORG_FADIGA_DURANTE_CONDUTA_MOTORA', 
    'BORG_FADIGA_FINAL_CONDUTA_MOTORA', 'BORG_FADIGA_INICIO_CONDUTA_MOTORA', 'CARGA_TREINAMENTO_MUSCULAR', 
    'CIRURGIA_EVOLUCAO', 'COAGULOGRAMA_EXAMES_LABORATORIAIS', 'COMUNICACAO_FSS', 'DEFICIT_MOTOR', 'DEFICIT_MOTOR_AUSENTE',
    'DEFICIT_MOTOR_NAO_AVALIADO', 'DEFICIT_MOTOR_PRESENTE', 'DIAGNOSTICO_BASE', 'ESTADO_MENTAL_FSS', 'FADIGA_DURANTE',
    'FADIGA_FINAL', 'FADIGA_INICIO', 'FC_EVOLUCAO', 'FIO2_SWEEP', 'FLUXO_VPM',
    'FORCA_MUSCALAR_MIE', 'FORCA_MUSCULAR_MID', 'FORCA_MUSCULAR_MSD', 'FORCA_MUSCULAR_MSE', 'FR_AUSCULTA_PULMONAR', 
    'FUNCAO_MOTORA_FSS', 'GASONOMETRIA_ARTERIAL', 'GLASGOW_EVOLUCAO', 'HEMOGRAMA_EXAMES_LABORITARIAIS',
    'HORARIO_HORA', 'HORARIO_MINUTO', 'NAO_AVALIADO_DESENVOLVIMENTO', 'NAO_TESTADO_PREENSAO_PALMAR', 'NAO_TESTADO_PRESSAO_PALMAR',
    'P0_1', 'PAM_EVOLUCAO', 'PAO2_FIO2_VPM', 'PA_EVOLUCAO', 'PEEP_MODO_PARAMETROS', 
    'PERME', 'PESO_TESTE_CAMINHA', 'PPICO_VPM', 
    'PRESSAO_CUFF', 'RAIO_X_EXAMES_IMAGEM', 'REPETICAO_TREINAMENTO_MUSCULAR',
    'RESPIRATORIO_FSS', 'RL', 'SENSORIAL_FSS', 'SERIE_TREINAMENTO_MUSCULAR', 'SETOR_DE_ORIGEM', 'SITUACAO_ATUAL',
    'SPO2_ALVO', 'SPO2_EVOLUCAO', 'SWEEP', 'TINSP_VENTILACAO_NAO_INVASIVA', 'TONUS_MUSCULAR', 'VALOR_PREDITO_TESTE_CAMINHADA', 'VO2', 'VOLUME_CORRENTE_ALVO_VPM', 
    'DS_DOCUMENTO', 'NM_SETOR', 'SENSIBILIDADE_VPM', 'BIA', 'NO', 'DATA_INICIO_VPM', 'DATA_INTERRUPCAO_VPM', 'DESMAME_VENTILATORIO',
    'EOT_PO', 'GRAU_DEPENDENCIA', 'INDICE_TOBIM', 'JOHN_HOPKINS', 'MUSCULAR_OUTROS', 'OUTROS_EXAMES_LABORITORIAIS',
    'POS_OPERATORIO_DATA', 'TIPO_VENO_ARTERIAL', 'NUMERO_COT', 'NUMERO_TQT', 'TUBO_T', 'MINUTOS_IOT'
}


# --------------------------------------
# Dicionário Mapeado Fichas - Psicologia
# 64, 919, 931, 932, 939, 1148, 1165
# --------------------------------------

#Mapeamento direto, trocando nomes de colunas
psico_ls = {
 
# --- LF ---
'em_tratamento':['DS_NAO_EM_TRATAMENTO_SAUDE_MENTAL_1', 'DS_SIM_EM_TRATAMENTO_SAUDE_MENTAL_1'],
'frequencia_pensamento_doenca':['RB_QUASE_NUNCA_FREQUENCIA_PENSAMENTOS_SOBRE_DOENCA_1',
                                'RB_AS_VEZES_FREQUENCIA_PENSAMENTOS_SOBRE_DOENCA_1',
                                'RB_FREQUENTEMENTE_PENSAMENTOS_SOBRE_DOENCA_1'],
'compreensao_saude':['RB_AUSENCIA_COMPREENSAO_REACOES_EMOCIONAIS_FRENTE_DIAGNOSTICO_CIRURGICA_CATEGORIAS_1',
                     'RB_BOA_COMPREENSAO_REACOES_EMOCIONAIS_FRENTE_DIAGNOSTICO_CIRURGICA_CATEGORIAS_1',
                     'RB_COMPREENSAO_PARCIAL_REACOES_EMOCIONAIS_FRENTE_DIAGNOSTICO_CIRURGICA_CATEGORIAS_1'],
'tipo_protese':['RB_SIM_PACIENTE_ALGUMA_INFORMACAO_NOCAO_HA_TIPOS_PROTESE_1',
                'RB_NAO_PACIENTE_ALGUMA_INFORMACAO_NOCAO_HA_TIPOS_PROTESE_1'],


}

#Atribuindo valores mapeados, binarios
psico_rn = {
    # --- ---
    'DS_NAO_EM_TRATAMENTO_SAUDE_MENTAL_1': 0, 'DS_SIM_EM_TRATAMENTO_SAUDE_MENTAL_1': 1,
    'RB_QUASE_NUNCA_FREQUENCIA_PENSAMENTOS_SOBRE_DOENCA_1': 0, 
    'RB_AS_VEZES_FREQUENCIA_PENSAMENTOS_SOBRE_DOENCA_1': 1,
    'RB_FREQUENTEMENTE_PENSAMENTOS_SOBRE_DOENCA_1': 2,
    'RB_AUSENCIA_COMPREENSAO_REACOES_EMOCIONAIS_FRENTE_DIAGNOSTICO_CIRURGICA_CATEGORIAS_1': 0,
    'RB_BOA_COMPREENSAO_REACOES_EMOCIONAIS_FRENTE_DIAGNOSTICO_CIRURGICA_CATEGORIAS_1': 1,
    'RB_COMPREENSAO_PARCIAL_REACOES_EMOCIONAIS_FRENTE_DIAGNOSTICO_CIRURGICA_CATEGORIAS_1': 2,
    'RB_NAO_PACIENTE_ALGUMA_INFORMACAO_NOCAO_HA_TIPOS_PROTESE_1': 0,
    'RB_SIM_PACIENTE_ALGUMA_INFORMACAO_NOCAO_HA_TIPOS_PROTESE_1': 1,
    

}

#Mapeamento direto, trocando nomes de colunas
psico_maps = {
    'cd_paciente': 'record_id', 
    'ds_tip_presc': 'tipo_atend_psico'
}

#Colunas para excluir
psico_cols_excluir = {
	'META_TERAPEUTICA_PSICOLOGIA_1':						'terapeutica_psicologia',
	'DS_COMO_DESCOBRIU_PROBLEMA_CARDIOLOGICO_1':			'problema_cardiologico',
	'DS_COMO_REAGIU_SABER_DIAGNOSTICO_1':					'saber_diagnostico',
	'DS_COMO_SENTIU_QUANDO_MEDICO_EXPLICOU_CIRURGIA_SERIA_NECESSARIA_CUIDAR_SAUDE_1':			'cuidar_saude',
	'DS_HA_ALGO_MAIS_GOSTARIA_COMPARTILHAR_SOBRE_DOENCA_SENTIMENTOS_ENVOLVIDOS_1':				'sentimentos_envolvidos',
	'DS_APOIO_AFETIVO_PONTUACAO_ESCALA_APOIO_SOCIAL_1':				'apoio_efetivo',
	'DS_QUEM_SERA_REDE_APOIO_APOS_CIRURGIA_ESCALA_APOIO_SOCIAL_1':	'rede_apoio',
	'DS_CONSEGUE_TOMAR_MEDICACOES_CONFORME_ORIENTADO_1':			'medicacao',
	'DS_QUE_OU_QUEM_CONSIDERA_APOIADO_NESTE_MOMENTO_ENFRENTAMENTO_IMPACTO_PESSOAL_1':			'apoio_momento',
	'DS_QUE_MUDOU_VIDA_DEPOIS_PROBLEMA_CARDIOLOGICO_ENFRENTAMENTO_IMPACTO_PESSOAL_1':			'problema_cardiologico_2',
	'DS_DEIXOU_REALIZAR_ALGUMA_ATIVIDADE_ENFRENTAMENTO_IMPACTO_PESSOAL_1':						'realizar_atividade',
	'DS_QUAIS_TEM_SIDO_PENSAMENTOS_ATITUDES_TEM_AJUDADO_CONVIVER_PROBLEMA_ENFRENTAMENTO_IMPACTO_PESSOAL_1':	'pensamento_atitudes',
	'DS_QUE_CONSIDERA_SIDO_MAIS_DIFICIL_NESTA_CONVIVENCIA_COM_DOENCA_ENFRENTAMENTO_IMPACTO_PESSOAL_1':		'convivencia_doenca',
	'DS_COSTUMA_PENSAR_SUA_DOENCA_COMO_FICA_FAZ_QUANDO_PENSAMENTOS_SURGEM_ENFRENTAMENTO_IMPACTO_PESSOAL_1':	'pensar_doenca',
	'DS_CONDUTA_ENCAMINHAMENTO_ESCALA_HADS_1':						'conduta_encaminhamento',
	'DS_TEM_FEITO_ALGO_PARA_SOLUCIONALAS_1':						'algo_solucao',
	'DS_SUAS_EXPECTATIVAS_DIANTE_PROCEDIMENTO_CIRURGICO_1':			'expectativas_procedimento',
	'DS_PREOCUPACOES_FRENTE_CIRURGIA_1':							'preocupacao_cirurgia',
	'DS_QUADROS_PSICOPATOLOGICOS_PREVIOS_ATUAIS_1':					'psicopatologicos',
	'DS_MEDICACOES_EM_USO_SAUDE_MENTAL_1':							'medicacao_uso',
	'DS_ESCORE_SINTOMAS_ANSIEDADE_PONTO_CORTE_8_1':					'hads_ansiedade',
	'DS_ESCORE_SINTOMAS_ANSIEDADE_PONTO_CORTE_9_1':					'hads_depressao',
	'DS_ME_ENFRENTAMENTO_FOCALIZADO_PROBLEMA_1':					'enf_problema',
	'DS_ME_ENFRENTAMENTO_FOCALIZADO_EMOCAO_1':						'enf_emocao',
	'RB_ME_BUSCA_PRATICAS_RELIGIOSAS_PENSAMENTO_FANTASIOSO_1':		'busca_religiosa',
	'RB_ME_BUSCA_SUPORTE_SOCIAL_1':									'busca_social',
	'DS_RECEBEU_APOIO_FAMILIAR_APOS_ADOECIMENTO_DE_QUEM_1':			'apoio_familiar',
	'DS_SUA_RELACOES_SOCIAIS_MUDARAM_APOS_ADOECIMENTO_1':			'relacao_social',
	'DS_APOIO_MATERIAL_PONTUACAO_ESCALA_APOIO_SOCIAL_1':			'apoio_material',
	'DS_APOIO_EMOCIONAL_INFORMACIONAL_PONTUACAO_ESCALA_APOIO_SOCIAL_1':							'apoio_emocional',
	'DS_INTERACAO_SOCIAL_AFETIVA_PONTUACAO_ESCALA_APOIO_SOCIAL_1':	'interacao_social',
	'DS_EXERCE_ATIVIDADE_REMUNERADA_ATUALMENTE_1':					'atividade_remunerada',
	'DS_SE_PACIENTE_CONTINUA_TRABALHANDO_ALGO_MUDOU_TRABALHO_1':	'alteracao_trabalho',
	'DS_SE_PAROU_TRABALHAR_COMO_FOI_PARA_VOCE_PARAR_TABALHAR_1':	'parou_trabalhar',
	'DS_SUAS_PREOCUPACOES_MOMENTO_1':								'preocupacao_momento',
	'CK_NEGACAO_PSC_1':												'reacoes___0', 
	'CK_MEDO_PSC_1':												'reacoes___1', 
	'CK_ANSIEDADE_PSC_1':											'reacoes___2', 
	'CK_TRISTEZA_PSC_1':											'reacoes___3',
	'CK_ALIVIO_PSC_1':												'reacoes___4', 
	'CK_ACEITACAO_PSC_1':											'reacoes___5', 
	'CK_ESPERANCA_PSC_1':											'reacoes___6', 
	'CK_INDIFERENCA_PSC_1':											'reacoes___7',
	'CK_OUTRAS_REACOES_EMOCIONAIS_1':								'reacoes___9',
	'TX_PSICOLOGIA_EVOLUCAO_1':										'evolucao_psicologia',
	'DS_SE_SIM_ESPECIFIQUE_SEU_CONHECIMENTO_PACIENTE_ALGUMA_INFORMACAO_NOCAO_HA_TIPOS_PROTESE_1':	'conhece_protese',
}


# --------------------------------------
# Dicionário Mapeado Fichas - Odontologia
# 241, 710, 891, 893, 894
# --------------------------------------

#Mapeamento direto, trocando nomes de colunas
odonto_ls = {
    'EFEO_CONTACT': ['CONTACTUANTE', 'CONTACTUANTE_NAO_VERBAL', 'CONTACTUANTE_VERBAL'],
    'EFEO_DEAMB': ['DEAMBULANTE', 'DEAMBULANTE_COM_AUXILIO', 'CADEIRANTE', 'ACAMADO'],
    'EFEO_DIETA': ['DIETA_ORAL', 'SNE', 'GTT', 'JEJUM'],
    'EFEO_RESPIR': ['SUPORTE_O2', 'ENTUBADO', 'TQT'],
    'EFIO_HIG_DONE':  ['HIGIENE_ORAL_SATISFATORIA', 'HIGIENE_ORAL_REGULAR', 'HIGIENE_ORAL_INSATISFATORIA'],
	'EFIO_HIG_WHO':  ['HIEGIENE_ORAL_PELO_PACIENTE', 'HIGIENE_ORAL_PELO_ACOMPANHANTE_CUIDADOR', 'HIGIENE_ORAL_PELA_ENFERMAGEM'],
    'EFIO_MUCOSA':  ['MUCOSA_INTEGRA', 'MUCOSA_RESSECADA', 'MUCOSA_CROSTA'],
    'EFIO_LABIO':  ['LABIO_INTEGRO', 'LABIO_RESSECADO', 'LABIO_CROSTA'],
    'EFIO_LINGUA':  ['LINGUA_INTEGRA', 'LINGUA_RESSECADA', 'LINGUA_COM_CROSTA', 'LINGUA_SABURRA', 'LINGUA_DESPAPILADA'],
    'EFIO_LESAO_TM':  ['TECIDOS_MOLES_COM_MUCOSA', 'TECIDOS_MOLES_COM_PALATO', 'TECIDO_MOLES_LINGUA', 'LABIO'],
                      
    'PCTE_URGENTE':  ['NAO_URG_EMERGENCIA', 'SIM_URG_EMERGENCIA', 'URGENCIA_E_EMERGENCIA_NAO', 'URGENCIA_E_EMERGENCIA_SIM'],
	'LIB_CIRURGIA':  ['LIBERACAO_CIRURGICA_NAO', 'LIBERACAO_CIRURGICA_SIM', 'NAO_LIBERACAO_CIRURGIA', 'SIM_LIBERACAO_CIRURGIA'],
    'PROTESE_DENTARIA': ['PROTESE_DENTARIA_NAO', 'PROTESE_DENTARIA_SIM'],
    'USO_ANTICOAG': ['FAZ_USO_DE_ANTICOAGULANTE', 'NAO_FAZ_USO_DE_ANTICOAGULANTE'],
    'USO_ANTIBIOT': ['PROFILAXIA_ANTIBIOTICA_NAO', 'PROFILAXIA_ANTIBIOTICA_SIM'],
    
    
}

#Atribuindo valores mapeados, binarios
odonto_rn = {
    
    'CONTACTUANTE':'Não Contactuante', 'CONTACTUANTE_NAO_VERBAL':'Contactuante Não Verbal', 'CONTACTUANTE_VERBAL':'Contactuante Verbal', 'DEAMBULANTE':'Deambulante', 
    'DEAMBULANTE_COM_AUXILIO':'Deambulante com Auxílio', 'CADEIRANTE':'Cadeirante', 'ACAMADO':'Acamado', 'DIETA_ORAL':'Dieta Oral', 'SNE':'SNE', 'SUPORTE_O2':'Suporte O2', 'GTT':'GGT', 
    'JEJUM':'Jejum', 'ENTUBADO':'Entubado', 'TQT':'TQT',
    'HIGIENE_ORAL_SATISFATORIA':'Satisfatória', 'HIGIENE_ORAL_REGULAR':'Regular', 'HIGIENE_ORAL_INSATISFATORIA':'Insatisfatória', 'HIEGIENE_ORAL_PELO_PACIENTE':'Paciente', 
    'HIGIENE_ORAL_PELO_ACOMPANHANTE_CUIDADOR':'Acompanhante/Cuidador', 'HIGIENE_ORAL_PELA_ENFERMAGEM':'Enfermagem',         
    'MUCOSA_INTEGRA':'Mucosa Integra', 'MUCOSA_RESSECADA':'Mucosa Ressecada', 'MUCOSA_CROSTA':'Mucosa com Crosta',
    'LABIO_INTEGRO':'Lábio Integro', 'LABIO_RESSECADO':'Lábio Ressecado', 'LABIO_CROSTA':'Lábio com Crosta',
    'LINGUA_INTEGRA':'Língua Integra', 'LINGUA_RESSECADA':'Língua Ressecada', 'LINGUA_COM_CROSTA':'Língua com Crosta', 'LINGUA_SABURRA':'Língua Saburra', 'LINGUA_DESPAPILADA':'Lingua Despapilada',
    'TECIDOS_MOLES_COM_MUCOSA':'Lesão Mucosa', 'TECIDOS_MOLES_COM_PALATO':'Lesão Palato', 'TECIDO_MOLES_LINGUA':'Lesão Língua', 'LABIO':'Lesão Lábio',
     
    'LIBERACAO_CIRURGICA_NAO': 0, 'LIBERACAO_CIRURGICA_SIM': 1, 'NAO_LIBERACAO_CIRURGIA': 0, 'SIM_LIBERACAO_CIRURGIA': 1,
    'NAO_URG_EMERGENCIA': 0, 'SIM_URG_EMERGENCIA': 1, 'URGENCIA_E_EMERGENCIA_NAO': 0, 'URGENCIA_E_EMERGENCIA_SIM': 1,
    'PROTESE_DENTARIA_NAO': 0, 'PROTESE_DENTARIA_SIM': 1,
    'FAZ_USO_DE_ANTICOAGULANTE': 1, 'NAO_FAZ_USO_DE_ANTICOAGULANTE': 0, 
    'PROFILAXIA_ANTIBIOTICA_SIM': 1, 'PROFILAXIA_ANTIBIOTICA_NAO': 0,

}

#Mapeamento direto, trocando nomes de colunas
odonto_maps = {
'CD_PACIENTE': 							'record_id',
'CD_ATENDIMENTO':                  'cd_atendimento',
'CARIE': 						'clinica_odonto___1',
'RAIZ_RESIDUAL': 				'clinica_odonto___2',
'CALCULO_DENTARIO': 			'clinica_odonto___3',
'GENGIVITE': 					'clinica_odonto___4',
'MOBILIDADE_DENTARIA': 			'clinica_odonto___5',
'PERIODONTITE': 				'clinica_odonto___6',
'LESAO_PERIAPICAL': 			'clinica_odonto___7',
'NECROSE_PULPAR': 				'clinica_odonto___8',
'PULPITE': 						'clinica_odonto___9',
'ABCESSO_DENTARIO': 			'clinica_odonto___10',
'ALVEOLITE': 					'clinica_odonto___11',
'PERICORONARITE': 				'clinica_odonto___12',
'RESTAURACAO_INSATISFATORIA': 	'clinica_odonto___13',
'PROTESE_FIXA': 				'clinica_odonto___14',
'IMPLANTE': 					'clinica_odonto___15',
'EDENTADO_TOTAL': 				'clinica_odonto___16',
'DENTADO_TOTAL': 				'clinica_odonto___17',
'DENTADO_PARCIAL': 				'clinica_odonto___18',
'FRATURA_DENTARIA': 			'clinica_odonto___19',

'PT_SUPERIOR': 					'tipo_protese_dentaria___1',
'PT_INFERIOR': 					'tipo_protese_dentaria___2',
'PPR_SUPERIOR': 				'tipo_protese_dentaria___3',
'PPR_INFERIOR': 				'tipo_protese_dentaria___4',

'IHO_S': 						'indice_ihos',
'SSIFICACAO': 					'classificacao_ihos',
'PREVALENCIA':					'prevalencia_cpod',
'NIVEL_PREVALENCIA':			'nivel_prevalencia_cpod',
'CARIADO':						'cariado_cpod',
'PERDIDO':						'perdido_cpod',
'OBTURADO':						'obturado_cpod',
'DENTE':						'dentes_cpod',

'SANGRAMENTO_SIM':				'odonto_outras_avaliacoes___1',
'FLUXO_SALIVAR_NORMAL':			'odonto_outras_avaliacoes___2',
'FLUXO_SALIVAR_SIALORREIA':		'odonto_outras_avaliacoes___3',
'FLUXO_SALIVAR_BABACAO':		'odonto_outras_avaliacoes___4',
'FLUXO_SALIVAR_XEROSTOMIA':		'odonto_outras_avaliacoes___5',
'FLUXO_SALIVAR_HIPOSSALIVACAO':	'odonto_outras_avaliacoes___6',
'CANDIASE_ORAL_SIM':			'odonto_outras_avaliacoes___7',
'HERPES_ORAL_SIM':				'odonto_outras_avaliacoes___8',
'DISFAGIA':						'odonto_outras_avaliacoes___9',
'DISTURBIO_PALADAR':			'odonto_outras_avaliacoes___10',
'TRISMO':						'odonto_outras_avaliacoes___11',
'DISTURBIOS_NEUROLOGICOS':		'odonto_outras_avaliacoes___12',
'PACIENTE_ALERGICO_SIM':		'odonto_outras_avaliacoes___13',
'PALIATIVO_SIM':				'odonto_outras_avaliacoes___14',
'DROGAS_ILICITAS':				'odonto_outras_avaliacoes___15',
'HIV':							'odonto_outras_avaliacoes___16',
'ALTERACOES_HEPATICAS':			'odonto_outras_avaliacoes___17',
'ALTERACOES_PULMONARES':		'odonto_outras_avaliacoes___18',
'ALTERACOES_RENAIS':			'odonto_outras_avaliacoes___19',

'GLICEMIA':						'exames_realizados_odonto___1', 
'TP':							'exames_realizados_odonto___2',
'RX_PANORAMICO':				'exames_realizados_odonto___3', 
'RX_PERIAPICAL':				'exames_realizados_odonto___4',
}

#Colunas para excluir
odonto_cols_excluir = {
	'CARDIOGERIATRIA', 'CONGENITO', 'CORONARIA', 'ELETROFISIOLOGIA', 'PEDIATRIA', 'SETOR_HIPERTENSAO', 'MARCA_PASSO', 
                'MIOCARDIO', 'TX_CARDIACO', 'TX_RENAL', 'VALVULA', 'VASCULAR', 'ANTICOAGULACAO', 'AMBULATORIO', 'INTERNADO', 'CENTRO_CIRURGICO', 
                'INTERNADO_UTI', 'INTERNADO_NA_UCO', 'INTERNADO_NA_ENFERMARIA', 'INTERNADO_NO_PRONTO_SOCORRO', 'PACIENTE_PRE_CIRURGICO_NAO', 
                'PACIENTE_PRE_CIRURGICO_SIM', 'PRE_CIRURGICO_NAO', 'PRE_CIRURGICO_SIM', 'PROBLEMA_COM_TRATAMENTO_ODONTOLOGICO_SIM',
                'PALIATIVO_NAO', 'PACIENTE_ALERGICO_NAO', 'SANGRAMENTO_NAO', 'CANDIASE_ORAL_NAO', 'HERPES_ORAL_NAO', 'VESTIBULAR_11_0',
                'VESTIBULAR_11_1', 'VESTIBULAR_11_2', 'VESTIBULAR_16_0', 'VESTIBULAR_16_1', 'VESTIBULAR_26_0', 'VESTIBULAR_26_1',
       			'VESTIBULAR_31_0', 'VESTIBULAR_31_1', 'VESTIBULAR_31_2', 'VESTIBULAR_31_3', 'LINGUAL_36_0',  'LINGUAL_36_1', 'LINGUAL_36_2',
                'LINGUAL_46_0', 'LINGUAL_46_1', 'LINGUAL_46_2', 'LISTA_EXODONTIA', 'LISTA_MEDICAMENTOS', 'LISTA_QTD_GENGIVECTOMIA', 'LISTA_QTD_RESTAURACAO',
                'LISTA_QTD_RX_PERIAPICAL', 'LISTA_QTD_SELAMENTO_PROVISORIO', 'LISTA_QTD_TRATAMENTO_ENDODONTICO', 'LISTA_QTD_TRATAMENTO_PERIODONTAL',
                'MEDICACAO', 'AVALIACAO_ODONTOLOGICA', 'ORIENTACOES_DE_HIGIENE_ORAL', 'REMOCAO_DE_SUTURA', 'BIOPSIA', 'LASERTERAPIA',
                'SELANTE_FLUOR', 'SELAMENTO_PROVISORIO', 'CONDICIONAMENTO', 'EXAMES_COMPLEMENTARES', 'EXODONTIA', 'EX_ETILISTA', 'EX_TABAGISTA',
                'REGISTRO_ODONTOLOGICO', 'REGULARIZACAO_OSSEA', 'REGULARIZAZAO_OSSEA', 'DLP', 'DM', 'DPOC', 'ETILISMO', 'GENGIVECTOMIA',
                'FREQUENCIA_HIGIENE_ORAL', 'OUTRAS_DOENCAS', 'OUTROS_PROCEDIMENTOS', 'PESO', 'PESO', 'PROBLEMA_ASSOCIADO_AO_TRATAMENTO_ODONTOLOGICO',
                'PT', 'QUEIXA_PRINCIPAL', 'RESTAURACAO', 'SEDENTARISMO', 'TABAGISMO_1', 'TELEFONE', 'TIPO_DE_CIRURGIA',
                'TRATAMENTO_ENDODONTICO', 'TRATAMENTO_ODONTOLOGICO', 'TRATAMENTO_ODONTOLOGICO_NAO', 'TRATAMENTO_PERIODONTAL', 
                'ATIVIDADE_FISICA', 'AVC_CEBEBRO_VASCULAR', 'A_TERAPEUTICA_ODONTO', 'ANTECEDENTES_PESSOAIS', 'HAS', 'PPR', 
                'VESTIBULAR_11_0', 'VESTIBULAR_11_1', 'VESTIBULAR_11_2', 'VESTIBULAR_11_3', 'VESTIBULAR_16_0', 'VESTIBULAR_16_1',
                'VESTIBULAR_16_2', 'VESTIBULAR_16_3', 'VESTIBULAR_26_0', 'VESTIBULAR_26_1', 'VESTIBULAR_26_2', 'VESTIBULAR_26_3',
                'VESTIBULAR_31_0', 'VESTIBULAR_31_1', 'VESTIBULAR_31_2', 'VESTIBULAR_31_3', 'LINGUAL_36_0', 'LINGUAL_36_1', 'LINGUAL_36_2',
                'LINGUAL_36_3', 'LINGUAL_46_0', 'LINGUAL_46_1', 'LINGUAL_46_2', 'LINGUAL_46_3', 'LISTA_EXODONTIA', 'LISTA_MEDICAMENTOS', 'LISTA_QTD_GENGIVECTOMIA',
                'LISTA_QTD_RESTAURACAO', 'LISTA_QTD_RX_PERIAPICAL', 'LISTA_QTD_SELAMENTO_PROVISORIO', 'LISTA_QTD_TRATAMENTO_ENDODONTICO', 'LISTA_QTD_TRATAMENTO_PERIODONTAL',
                'MEDICACAO', 'NAO_SE_APLICA_IHOS',

}

#Mapeamento de procedimentos
odonto_procedimentos = {
    # --- diagnostico_triagem ---
    'PRIMEIRA CONSULTA ODONTOLOGICA PROGRAMATICA': 'diagnostico_triagem',
    'CONSULTA DE PROFISSIONAIS DE NIVEL SUPERIOR NA ATENÇÃO ESPEC': 'diagnostico_triagem',
    'TRATAMENTO ODONT. PARA PACIENTES COM NECESSIDADES ESPECIAIS': 'diagnostico_triagem',
    'CONSULTA OFTALMOLOGIA': 'diagnostico_triagem', # (Outlier, mas é consulta)
    'RX PANORAMICA DE MANDIBULA (ORTOPANTOMOGRAFIA)': 'diagnostico_triagem',
    'RADIOGRAFIA PERIAPICAL - INTERPROXIMAL': 'diagnostico_triagem',
    'TC DE SEIOS DA FACE': 'diagnostico_triagem',
    'TP TEMPO DE PROTROMBINA': 'diagnostico_triagem',
    'COLETA DE RASPADO EM LESOES OU SITIOS ESPE DA REGI': 'diagnostico_triagem',

    # --- prevencao_higiene ---
    'ORIENTAÇÃO DE HIGIENE BUCAL': 'prevencao_higiene',
    'REALIZAR HIGIENE ORAL - ESCOVAÇÃO COM CLOREXIDINA 0,12%': 'prevencao_higiene',
    'PROFILAXIA REMOÇÃO DA PLACA BACTERIANA': 'prevencao_higiene',
    'ORIENTAÇÃO DE HIGIENIZAÇÃO DAS PROTESES DENTARIAS': 'prevencao_higiene',
    'REALIZAR AUXILIAR HIGIENE ORAL DO PACIENTE PARA CONFORTO': 'prevencao_higiene',
    'SALIVA ARTIFICAL (GEL UMECTANTE)': 'prevencao_higiene',

    # --- periodontia (GENGIVA) ---
    'RASPAGEM CORONO-RADICULAR (POR SEXTANTE)': 'periodontia',
    'RASPAGEM ALISAMENTO E POLIMENTO SUPRAGENGIVAL (POR SEXTANTE)': 'periodontia',
    'RASPAGEM ALISAMENETO SUBGENGIVAL (POR SEXTANTE)': 'periodontia',

    # --- dentistica (RESTAURAÇÃO) ---
    'RESTAURACAO DE DENTE PERMANENTE ANTERIOR': 'dentistica',
    'RESTAURAÇÃO DENTE PERMANENTE POSTERIOR': 'dentistica',
    'RESTAURAÇÃO DENTE PERMANENTE ANTERIOR': 'dentistica', # Repetido na lista original
    'RESTAURACAO EM RESINA FOTOPOLIMERIZAVEL 1 FACE': 'dentistica',
    'RESTAURACAO EM RESINA FOTOPOLIMERIZAVEL 2 FACES': 'dentistica',
    'SELAMENTO PROVISÓRIO CAVIDADE': 'dentistica',

    # --- endodontia (CANAL) ---
    'TRATAMENTO ENDODONTICO BIRRADICULAR': 'endodontia',
    'TRATAMENTO ENDODONTICO UNIRRADICULAR': 'endodontia',
    'TRATAMENTO ENDODONTICO MULTIRRADICULAR': 'endodontia',
    'RETRATAMENTO ENDODONTICO EM DENTE PERMANENTE UNI-RADICULAR': 'endodontia',
    'RETRATAMENTO ENDODONTICO EM DENTE PERMANENTE BI-RADICULAR': 'endodontia',
    'ACESSO A POLPA DENTÁRIA E MEDICAÇÃO (POR DENTE)': 'endodontia',
    'CAPEAMENTO PULPAR': 'endodontia',
    'CURATIVO DEMORA COM OU SEM PREPARO BIOMECÂNICO': 'endodontia',
    'SELAMENTO DE PERFURAÇÃO RADICULAR': 'endodontia',

    # --- cirurgia_oral ---
    'EXODONTIA DENTES PERMANENTES': 'cirurgia_oral',
    'EXODONTIA DE RAIZ RESIDUAL': 'cirurgia_oral',
    'EXODONTIA A RETALHO': 'cirurgia_oral',
    'CURETAGEM PERIAPICAL': 'cirurgia_oral',
    'CURETAGEM APICAL': 'cirurgia_oral',
    'ODONTOSECÇÃO / RADILECTOMIA / TUNELIZAÇÃO': 'cirurgia_oral',
    'ODONTO-SECCAO': 'cirurgia_oral',
    'CORREÇÃO DE IRREGULARIDADES DE REBORDO ALVEOLAR': 'cirurgia_oral',
    'BIOPSIA DOS TECIDOS MOLES DA BOCA': 'cirurgia_oral',
    'TRATAMENTO CIRURGICO DE HEMORRAGIA BUCAL DENTAL': 'cirurgia_oral',
    'CONTR DE HEMORRAGIA C/APLIC DE AGENTE HEMOST EM REG BUCO-M': 'cirurgia_oral',
    'RETIRADA DE PONTOS DE CIRURGIA BASICA (POR PACIENTE)': 'cirurgia_oral',

    # --- farmacoterapia E ANESTESIA ---
    'AMOXICILINA 500 MG CP': 'farmacoterapia',
    'CLINDAMICINA 300 MG CP': 'farmacoterapia',
    'DIPIRONA 500 MG CP': 'farmacoterapia',
    'DEXAMETASONA 4 MG/ML AMP 2,5 ML': 'farmacoterapia',
    'CAPTOPRIL 25 MG CP': 'farmacoterapia',
    'ACIDO EPSILON  AMINOCAPROICO 50 MG/ML (1G) FAMP 20 ML': 'farmacoterapia',
    'ACIDO EPSILON AMINOCAPROICO 50 MG/ML (1G) FAMP 20 ML': 'farmacoterapia',
    'ACIDOS GRAXOS ESSENCIAIS OLEO CICATRIZANTE FR 200 ML': 'farmacoterapia',
    'LIDOCAINA+EPINEFRINA(2% + 1:100000) TUBETE 1,8 ML ODONTO': 'farmacoterapia',
    'LIDOCAINA + EPINEFRINA (2%+1:100000) TUBETE 1,8 ML ODONTO': 'farmacoterapia',

    # --- TERAPIAS ADJUVANTES / SUPORTE ---
    'APLICAÇÃO DE LASER TERAPEUTICO': 'laserterapia',
    'APLICACAO DE LASER TERAPEUTICO': 'laserterapia',
    'DIETA PASTOSA': 'suporte_hospitalar',
    'DIETA PASTOSA DIABETICO 40G': 'suporte_hospitalar',
    
	# --- LIBERAÇÃO CIRURGICA ---
    'LIBERAÇÃO ODONTOLOGICA PARA CIRURGIA CARDIACA': 'lib_cirurgia'
}


odonto_proced_maps = {
	'cirurgia_oral': 			'atividades_odonto___1',
	'dentistica': 				'atividades_odonto___2',
	'diagnostico_triagem': 		'atividades_odonto___3',
	'endodontia': 				'atividades_odonto___4',
	'farmacoterapia': 			'atividades_odonto___5',
	'laserterapia': 			'atividades_odonto___6',
	'periodontia': 				'atividades_odonto___7',
	'prevencao_higiene': 		'atividades_odonto___8',
	'suporte_hospitalar': 		'atividades_odonto___9',

}



# --------------------------------------
# Dicionário Mapeado Fichas - CORONARIAS - PRE/POS OPERATORIO
# 938, 942, 943, 1031, 1072, 1073, 1115, 1173
# --------------------------------------

#Mapeamento direto, trocando nomes de colunas
coron_ls = {
    'ISOLAMENTO': ['SN_ISOLA_SIM_1', 'SN_ISOLA_NAO_1'],
    'SEDENTARISMO': ['SN_SEDENTARISMO_1'],
    'etilista': ['SN_ETILISMO_1'],
    'ATIVIDADE FISICA': ['SN_ATIVIDADE_FISICA_1'],
    'EDEMA': ['SN_ENDEMA_1'],
    'TONTURA': ['SN_TONTURA_1'],
    'dac_exame': ['SN_DAC_1'],
	

    
    
}

#Atribuindo valores mapeados, binarios
coron_rn = {
    
    'SN_ISOLA_SIM_1':1, 'SN_ISOLA_NAO_1':0,
    'SN_SEDENTARISMO_1':1,
    'SN_ETILISMO_1':2,
    'SN_ATIVIDADE_FISICA_1':1,
    'SN_ENDEMA_1':1,
    'SN_ANGINA_1':1,
    'SN_DAC_1':1,

    
}

#Mapeamento direto, trocando nomes de colunas
coron_maps = {
    'CD_PACIENTE': 						'record_id',
    'CD_ATENDIMENTO':                   'cd_atendimento',
    'DS_PESO_1': 						'peso',
    'DS_ALTURA_1': 						'altura',
    'DS_IMC_1': 						'imc',

    'DS_OUTROS_ANTECEDENTES_PESSOAIS_1': 	'outros_antecedentes_pessoais',
    'DS_OBSERVACOES_1':                     'final_observacao',
    'DS_MEDICAMENTOS_1':                    'medicacoes_outros',
    'DS_CIRC_ABDOMINAL_1':                  'circ_abdomen_cm',

}

#Colunas para excluir
coron_cols_excluir = {
	'ISOLAMENTO', 'SEDENTARISMO', 'ATIVIDADE FISICA', 'EDEMA', 'DS_FR_1', 'DS_TEMPERATURA_1',
    'DS_PAS_1', 'DS_QUEIXAS_1', 'DT_CIRURGIA_1', 'DS_HORA_PROGRAMADA_1', 'DS_MINUTOS_PROGRAMADO_1',
    'DS_ALERGIA_1', 'DS_DIAGNOSTICO_1', 'DS_CIRURGIA_AVISO_1', 'IMG_ANEURISMA_ABDOMINAL_1',
    'IMG_CIRURGIA_TORACIA_1', 'IMG_CONGENITO_E_VALVULAR_1', 'IMG_ENDARTERECTOMIA_1', 'IMG_ENXERTO_ARTERIAL_1',
    'IMG_FASCIOTOMIA_1', 'IMG_IMPLANTE_DE_DESFIBRILADOR_1', 'IMG_IMPLANTE_DE_MARCAPASSO_DEFINITIVO_1', 'IMG_MARFAN_1',
    'IMG_PSEUDO_ANEURISMA_BRAQUIAL_1', 'IMG_PSEUDO_ANEURISMA_FEMURAL_1', 'IMG_REVASCULARIZACAO_DO_MIOCARDIO_1', 
    'IMG_SAFENECTOMIA_1', 'IMG_SIMPATECTOMIA_1',



}

#Mapeamento de procedimentos